import type { Language, QuantityUnit } from '@/types';

interface SeedProductTranslation {
  uz: string;
  en: string;
}

const productTranslations: Record<string, SeedProductTranslation> = {
  'TB-001': { uz: 'Chiqindi paketlari 45×50 sm, 20 l, 40 dona', en: 'Refuse bags 45×50 cm, 20 L, 40 pcs' },
  'TB-002': { uz: 'Chiqindi paketlari 45×60 sm, 22 l, 30 dona', en: 'Refuse bags 45×60 cm, 22 L, 30 pcs' },
  'TB-003': { uz: 'Chiqindi paketlari 50×70 sm, 41 l, 25 dona', en: 'Refuse bags 50×70 cm, 41 L, 25 pcs' },
  'TB-004': { uz: 'Chiqindi paketlari 60×90 sm, 85 l, 9 dona', en: 'Refuse bags 60×90 cm, 85 L, 9 pcs' },
  'TB-005': { uz: 'Chiqindi paketlari 80×110 sm, 160 l, 7 dona', en: 'Refuse bags 80×110 cm, 160 L, 7 pcs' },
  'TB-006': { uz: 'Chiqindi qoplari 90×110 sm, 200 l, 7 dona', en: 'Refuse sacks 90×110 cm, 200 L, 7 pcs' },
  'TB-007': { uz: 'Chiqindi paketlari 90×120 sm, 240 l, 6 dona', en: 'Refuse bags 90×120 cm, 240 L, 6 pcs' },
  'TB-008': { uz: 'Chiqindi paketlari 90×120 sm, 240 l, 11 dona', en: 'Refuse bags 90×120 cm, 240 L, 11 pcs' },
  'TO-001': { uz: 'Uziladigan o‘ta mustahkam paketlar 19×27 sm, 222 dona', en: 'Extra-strong perforated bags 19×27 cm, 222 pcs' },
  'TO-002': { uz: 'Uziladigan o‘ta mustahkam paketlar 28×38 sm, 303 dona', en: 'Extra-strong perforated bags 28×38 cm, 303 pcs' },
  'CB-001': { uz: '«Mayka» paketlari 3 kg, o‘ta mustahkam, 50 dona', en: 'Extra-strong T-shirt bags, 3 kg, 50 pcs' },
  'CB-002': { uz: '«Mayka» paketlari 5 kg, o‘ta mustahkam, 50 dona', en: 'Extra-strong T-shirt bags, 5 kg, 50 pcs' },
  'CB-003': { uz: '«Mayka» paketlari 10 kg, o‘ta mustahkam, 30 dona', en: 'Extra-strong T-shirt bags, 10 kg, 30 pcs' },
  'CB-004': { uz: '«Mayka» paketlari 25 kg, o‘ta mustahkam, 25 dona', en: 'Extra-strong T-shirt bags, 25 kg, 25 pcs' },
  'CB-005': { uz: '«Mayka» paketlari 50 kg, o‘ta mustahkam, 25 dona', en: 'Extra-strong T-shirt bags, 50 kg, 25 pcs' },
  'VB-001': { uz: 'Vakuum paketlari 15×25 sm', en: 'Vacuum bags 15×25 cm' },
  'VB-002': { uz: 'Vakuum paketlari 20×25 sm', en: 'Vacuum bags 20×25 cm' },
  'VB-003': { uz: 'Vakuum paketlari 25×35 sm', en: 'Vacuum bags 25×35 cm' },
  'PB-001': { uz: 'Universal pitsa paketlari 25/30/35 sm, 40 dona', en: 'Universal pizza bags 25/30/35 cm, 40 pcs' },
  'FP-001': { uz: 'Katta streych plyonka, 45 sm', en: 'Large stretch film, 45 cm' },
  'FP-002': { uz: 'Kichik streych plyonka, 30 sm', en: 'Small stretch film, 30 cm' },
  'FP-003': { uz: 'Katta folga, 2 kg, 45 sm', en: 'Large aluminium foil, 2 kg, 45 cm' },
  'FP-004': { uz: 'Pishirish qog‘ozi 37 sm × 40 m', en: 'Baking paper 37 cm × 40 m' },
  'GL-001': { uz: 'Universal polietilen qo‘lqoplar, 100 dona', en: 'Universal polyethylene gloves, 100 pcs' },
  'GL-002': { uz: 'Mikky sariq rezina qo‘lqoplari L, 2 dona', en: 'Mikky yellow rubber gloves, size L, 2 pcs' },
  'GL-003': { uz: 'Mikky sariq qalin idish yuvish qo‘lqoplari L, 2 dona', en: 'Mikky yellow heavy-duty washing-up gloves, size L, 2 pcs' },
  'GL-004': { uz: 'Touch Flex qora rezina qo‘lqoplari XL/L/M, 100 dona', en: 'Touch Flex black rubber gloves XL/L/M, 100 pcs' },
  'CL-001': { uz: '«Delfin» tozalash lattasi, 1 dona', en: 'Dolphin cleaning cloth, 1 pc' },
  'CL-002': { uz: 'Idish yuvish gubkalari, 3 dona', en: 'Dishwashing sponges, 3 pcs' },
  'CL-003': { uz: 'Stol uchun rangli lattalar, 3 dona', en: 'Coloured table cloths, 3 pcs' },
  'CL-004': { uz: 'Koreys gubkasi, 1 dona', en: 'Korean cleaning sponge, 1 pc' },
  'CL-005': { uz: 'Mikrofibrali pol lattasi', en: 'Microfibre floor cloth' },
  'PG-001': { uz: 'Rulonli salfetkalar, 2 qatlamli, 2 rulon', en: 'Two-ply roll towels, 2 rolls' },
  'PG-002': { uz: 'V shaklidagi salfetkalar 19,5×10,5 sm, 150 dona', en: 'V-fold napkins 19.5×10.5 cm, 150 pcs' },
  'PG-003': { uz: 'Z shaklidagi salfetkalar, 180 dona', en: 'Z-fold napkins, 180 pcs' },
  'PG-004': { uz: 'Kvadrat salfetkalar 23×23 sm, 100 dona', en: 'Square napkins 23×23 cm, 100 pcs' },
  'PG-005': { uz: 'Longper Premium salfetkalari, 40 dona', en: 'Longper Premium napkins, 40 pcs' },
  'PG-006': { uz: 'Ikki qatlamli tualet qog‘ozi, 6 rulon', en: 'Two-ply toilet paper, 6 rolls' },
  'PG-007': { uz: 'Nam salfetkalar, 300 donali blok', en: 'Wet wipes, block of 300' },

  'BF-001': { uz: 'Bon-file', en: 'Beef tenderloin' },
  'BF-002': { uz: 'Tozalanmagan bon-file', en: 'Untrimmed beef tenderloin' },
  'BF-003': { uz: 'Kontr-file', en: 'Beef striploin' },
  'BF-004': { uz: 'Mol go‘shti kachalkasi', en: 'Beef eye of round' },
  'BF-005': { uz: 'Mol bo‘yni', en: 'Beef neck' },
  'BF-006': { uz: 'Mol go‘shti tranchi', en: 'Beef knuckle' },
  'BF-007': { uz: 'Tashqi son go‘shti', en: 'Beef outside round' },
  'BF-008': { uz: 'Mol charvisi', en: 'Beef fat' },
  'BF-009': { uz: 'Mol go‘shti shapogi (pashina)', en: 'Beef flank' },
  'BF-010': { uz: 'Sarpanja', en: 'Beef plate' },
  'BF-011': { uz: 'Mol qovurg‘asi', en: 'Beef ribs' },
  'BF-012': { uz: 'Mol go‘shtli ragu', en: 'Beef stew meat' },
  'CH-001': { uz: 'Tovuq ko‘krak go‘shti', en: 'Chicken breast' },
  'CH-002': { uz: 'Tozalangan tovuq ko‘krak go‘shti', en: 'Trimmed chicken breast' },
  'CH-003': { uz: 'Tovuq soni', en: 'Chicken thigh' },
  'CH-004': { uz: 'Suyaksiz tovuq soni', en: 'Boneless chicken thigh' },
  'CH-005': { uz: 'Suyaksiz va terisiz tovuq soni', en: 'Boneless skinless chicken thigh' },
  'CH-006': { uz: 'Tovuq boldiri', en: 'Chicken drumstick' },
  'CH-007': { uz: 'Tovuq son go‘shti', en: 'Chicken leg quarter' },
  'CH-008': { uz: 'Tovuq qanotlari', en: 'Chicken wings' },
  'CH-009': { uz: 'Butun tovuq, 2–2,5 kg', en: 'Whole chicken, 2–2.5 kg' },
  'EG-001': { uz: 'Tovuq tuxumi', en: 'Chicken egg' },

  'FL-001': { uz: '«Dani Nan» oliy navli un, 50 kg', en: 'Dani Nan premium flour, 50 kg' },
  'FL-002': { uz: '«Dani Nan» oliy navli un, 25 kg', en: 'Dani Nan premium flour, 25 kg' },
  'FL-003': { uz: '«Dani Nan» 1-navli un, 50 kg', en: 'Dani Nan first-grade flour, 50 kg' },
  'FL-004': { uz: '«Dani Nan» 1-navli un, 25 kg', en: 'Dani Nan first-grade flour, 25 kg' },
  'FL-005': { uz: '«Oltin Nan» oliy navli un, 50 kg', en: 'Altyn Nan premium flour, 50 kg' },
  'FL-006': { uz: '«Oltin Nan» 1-navli un, 50 kg', en: 'Altyn Nan first-grade flour, 50 kg' },
  'FL-007': { uz: '«Mo‘tabar» oliy navli un, 50 kg', en: 'Mutabar premium flour, 50 kg' },
  'FL-008': { uz: '«Mo‘tabar» 1-navli un, 50 kg', en: 'Mutabar first-grade flour, 50 kg' },
  'SG-001': { uz: 'Rossiya shakari, 50 kg', en: 'Russian sugar, 50 kg' },
  'GR-001': { uz: '«Lazer» guruchi', en: 'Lazer rice' },
  'GR-002': { uz: '«Alanga» guruchi', en: 'Alanga rice' },
  'GR-003': { uz: 'Grechka', en: 'Buckwheat' },
  'GR-004': { uz: 'Yasmiq', en: 'Lentils' },
  'GR-005': { uz: 'Amerika no‘xati', en: 'American chickpeas' },
  'GR-006': { uz: 'Eron no‘xati', en: 'Iranian chickpeas' },
  'OI-001': { uz: '«Oleyna» kungaboqar moyi, 5 l', en: 'Oleyna sunflower oil, 5 L' },

  'FR-001': { uz: 'Yirik Misr apelsini', en: 'Large Egyptian orange' },
  'FR-002': { uz: 'Mayda Misr apelsini', en: 'Small Egyptian orange' },
  'FR-003': { uz: 'Argentina limoni', en: 'Argentinian lemon' },
  'FR-004': { uz: 'Chili kivisi', en: 'Chilean kiwi' },
  'FR-005': { uz: 'Afrika greypfruti', en: 'African grapefruit' },
  'FR-006': { uz: 'Ekvador banani', en: 'Ecuadorian banana' },
  'FR-007': { uz: 'Silliq avokado', en: 'Smooth-skinned avocado' },
  'FR-008': { uz: 'Hass avokadosi', en: 'Hass avocado' },
  'FR-009': { uz: 'Ananas (Xitoy)', en: 'Pineapple (China)' },
  'FR-010': { uz: 'Limon (Xitoy)', en: 'Lemon (China)' },
  'FR-011': { uz: 'Mahalliy limon', en: 'Local lemon' },
  'FR-012': { uz: 'Laym', en: 'Lime' },
  'FR-013': { uz: 'Kivi (Xitoy)', en: 'Kiwi (China)' },
  'FR-014': { uz: 'Marakuya (Xitoy)', en: 'Passion fruit (China)' },
  'FR-015': { uz: 'Marakuya (Tailand)', en: 'Passion fruit (Thailand)' },
  'FR-016': { uz: 'Sariq mini mango', en: 'Yellow mini mango' },
  'FR-017': { uz: 'Mango (Peru)', en: 'Mango (Peru)' },
  'FR-018': { uz: 'Oq shaftoli', en: 'White peach' },
  'FR-019': { uz: 'Granny Smith olmasi', en: 'Granny Smith apple' },
  'FR-020': { uz: 'Saltanat olmasi', en: 'Saltanat apple' },
  'FR-021': { uz: 'Shine Muscat uzumi', en: 'Shine Muscat grapes' },
  'FR-022': { uz: 'Rizamat uzumi', en: 'Rizamat grapes' },
  'BR-001': { uz: 'Golubika, 500 g', en: 'Blueberries, 500 g' },
  'BR-002': { uz: 'Golubika, 125 g', en: 'Blueberries, 125 g' },
  'BR-003': { uz: 'Maymunjon, 125 g', en: 'Blackberries, 125 g' },
  'BR-004': { uz: 'Qoraqat, 125 g', en: 'Blackcurrants, 125 g' },
  'BR-005': { uz: 'Fizalis, 125 g', en: 'Physalis, 125 g' },
  'BR-006': { uz: 'Malina, 125 g', en: 'Raspberries, 125 g' },
  'BR-007': { uz: 'Qulupnay', en: 'Strawberries' },
  'VG-001': { uz: 'Pekin karami', en: 'Chinese cabbage' },
  'VG-002': { uz: 'Sabzi', en: 'Carrots' },
  'VG-003': { uz: 'Bosh piyoz', en: 'Onions' },
  'VG-004': { uz: 'Kartoshka', en: 'Potatoes' },
  'VG-005': { uz: 'Pink Paradise pomidori', en: 'Pink Paradise tomato' },
  'VG-006': { uz: 'Qizil pomidor', en: 'Red tomato' },
  'VG-007': { uz: 'Rava bodringi', en: 'Rava cucumbers' },
  'VG-008': { uz: 'Orzu bodringi', en: 'Orzu cucumbers' },
  'VG-009': { uz: 'Zanjabil', en: 'Ginger' },
  'VG-010': { uz: '«Svetofor» bulg‘or qalampiri', en: 'Traffic Light sweet peppers' },
  'VG-011': { uz: 'Tozalangan sarimsoq', en: 'Peeled garlic' },
  'VG-012': { uz: 'Shampinyonlar', en: 'Button mushrooms' },
  'VG-013': { uz: 'Sarsabil', en: 'Asparagus' },

  'GN-001': { uz: 'Novagreen Aysberg salati, 500 g', en: 'Novagreen iceberg lettuce, 500 g' },
  'GN-002': { uz: 'Novagreen latuk salati, 500 g', en: 'Novagreen lettuce, 500 g' },
  'GN-003': { uz: 'Novagreen Romano salati, 500 g', en: 'Novagreen romaine lettuce, 500 g' },
  'GN-004': { uz: 'Novagreen rukkolasi', en: 'Novagreen rocket' },
  'GN-006': { uz: 'Novagreen ismaloqi', en: 'Novagreen spinach' },
  'GN-008': { uz: 'Novagreen Lollo Rosso salati, 500 g', en: 'Novagreen Lollo Rosso lettuce, 500 g' },
  'GN-009': { uz: 'Novagreen keyli, 500 g', en: 'Novagreen kale, 500 g' },
  'GN-010': { uz: 'Novagreen mangoldi', en: 'Novagreen chard' },
  'GN-012': { uz: 'Novagreen selderey poyasi, 1 dona', en: 'Novagreen celery stalk, 1 pc' },
  'GN-013': { uz: 'Novagreen rozmarini', en: 'Novagreen rosemary' },
  'GN-016': { uz: 'Novagreen yalpizi', en: 'Novagreen mint' },
  'GN-018': { uz: 'Novagreen kashnichi', en: 'Novagreen coriander' },
  'GN-020': { uz: 'Novagreen ukropi', en: 'Novagreen dill' },
  'GN-022': { uz: 'Novagreen golland petrushkasi', en: 'Novagreen Dutch parsley' },
  'GN-024': { uz: 'Novagreen petrushkasi, 500 g', en: 'Novagreen parsley, 500 g' },
  'GN-025': { uz: 'Novagreen qo‘zichoq piyozi, 500 g', en: 'Novagreen lamb onion, 500 g' },
  'GN-026': { uz: 'Novagreen ko‘k piyozi, 500 g', en: 'Novagreen spring onions, 500 g' },
  'GN-027': { uz: 'Novagreen rediskasi, 500 g', en: 'Novagreen radishes, 500 g' },
  'GN-028': { uz: 'Novagreen seldereyi, 500 g', en: 'Novagreen celery, 500 g' },
  'GN-029': { uz: 'Novagreen to‘g‘ralgan Aysberg salati, 500 g', en: 'Novagreen shredded iceberg lettuce, 500 g' },
  'MG-001': { uz: 'Novagreen amarant mikroko‘kati, 1 dona', en: 'Novagreen amaranth microgreens, 1 pc' },
  'MG-002': { uz: 'Novagreen brokkoli mikroko‘kati, 1 dona', en: 'Novagreen broccoli microgreens, 1 pc' },
  'MG-003': { uz: 'Novagreen no‘xat mikroko‘kati, 1 dona', en: 'Novagreen pea shoots, 1 pc' },
  'MG-004': { uz: 'Novagreen xantal mikroko‘kati, 1 dona', en: 'Novagreen mustard microgreens, 1 pc' },
  'MG-005': { uz: 'Novagreen daykon mikroko‘kati, 1 dona', en: 'Novagreen daikon microgreens, 1 pc' },
  'MG-006': { uz: 'Novagreen qizil rediska mikroko‘kati, 1 dona', en: 'Novagreen red radish microgreens, 1 pc' },
  'MG-007': { uz: 'Novagreen kress-salat mikroko‘kati, 1 dona', en: 'Novagreen cress microgreens, 1 pc' },
  'MG-008': { uz: 'Novagreen latuk mikroko‘kati, 1 dona', en: 'Novagreen lettuce microgreens, 1 pc' },
  'MG-009': { uz: 'Novagreen rediska mikroko‘kati, 1 dona', en: 'Novagreen radish microgreens, 1 pc' },
  'MG-010': { uz: 'Novagreen rukkola mikroko‘kati, 1 dona', en: 'Novagreen rocket microgreens, 1 pc' },
  'MG-011': { uz: 'Novagreen «Yeyiladigan gullar» mikroko‘kati, 1 dona', en: 'Novagreen edible flowers, 1 pc' },
  'MG-012': { uz: 'Novagreen shovul mikroko‘kati, 1 dona', en: 'Novagreen sorrel microgreens, 1 pc' },

  'DA-001': { uz: 'Fin sariyog‘i, 500 g', en: 'Fin butter, 500 g' },
  'DA-002': { uz: 'Valio sariyog‘i, 1 kg', en: 'Valio butter, 1 kg' },
  'DA-003': { uz: 'Valio sariyog‘i, 500 g', en: 'Valio butter, 500 g' },
  'DA-004': { uz: 'Svalya sariyog‘i', en: 'Svalya butter' },
  'DA-006': { uz: 'Viola Cheese Burger pishlog‘i, 8 bo‘lak', en: 'Viola Cheese Burger cheese, 8 slices' },
  'DA-007': { uz: 'Viola Creamy pishlog‘i, 8 bo‘lak', en: 'Viola Creamy cheese, 8 slices' },
  'DA-008': { uz: 'Viola qaymoqli pishlog‘i, 400 g', en: 'Viola cream cheese, 400 g' },
  'DA-009': { uz: 'Fitaki pishlog‘i, 500 g', en: 'Fitaki cheese, 500 g' },
  'DA-010': { uz: 'Dor Blue pishlog‘i, 2,5 kg', en: 'Dor Blue cheese, 2.5 kg' },
  'DA-011': { uz: 'Camembert pishlog‘i, 500 g', en: 'Camembert cheese, 500 g' },
  'DA-012': { uz: 'Brie pishlog‘i, 500 g', en: 'Brie cheese, 500 g' },
  'DA-013': { uz: 'Svalya pishlog‘i, 3 kg', en: 'Svalya cheese, 3 kg' },
  'OI-002': { uz: 'Unity fritür moyi, 10 l', en: 'Unity frying oil, 10 L' },
};

const attributeValueTranslations: Record<string, SeedProductTranslation> = {
  'полиэтиленовые': { uz: 'Polietilen', en: 'Polyethylene' },
  'резиновые': { uz: 'Rezina', en: 'Rubber' },
  'резиновые утолщённые': { uz: 'Qalin rezina', en: 'Heavy-duty rubber' },
  '2 слоя': { uz: '2 qatlam', en: '2 ply' },
  'говядина': { uz: 'Mol go‘shti', en: 'Beef' },
  'курица': { uz: 'Tovuq go‘shti', en: 'Chicken' },
  'высший сорт': { uz: 'Oliy nav', en: 'Premium grade' },
  '1 сорт': { uz: '1-nav', en: 'First grade' },
  'Россия': { uz: 'Rossiya', en: 'Russia' },
  'США': { uz: 'AQSH', en: 'United States' },
  'Иран': { uz: 'Eron', en: 'Iran' },
  'рис': { uz: 'Guruch', en: 'Rice' },
  'Египет': { uz: 'Misr', en: 'Egypt' },
  'Аргентина': { uz: 'Argentina', en: 'Argentina' },
  'Чили': { uz: 'Chili', en: 'Chile' },
  'Африка': { uz: 'Afrika', en: 'Africa' },
  'Эквадор': { uz: 'Ekvador', en: 'Ecuador' },
  'Китай': { uz: 'Xitoy', en: 'China' },
  'Узбекистан': { uz: 'O‘zbekiston', en: 'Uzbekistan' },
  'Таиланд': { uz: 'Tailand', en: 'Thailand' },
  'Перу': { uz: 'Peru', en: 'Peru' },
  'крупный': { uz: 'Yirik', en: 'Large' },
  'мелкий': { uz: 'Mayda', en: 'Small' },
  'гладкий': { uz: 'Silliq po‘stli', en: 'Smooth-skinned' },
  'жёлтый мини': { uz: 'Sariq mini', en: 'Yellow mini' },
  'белый': { uz: 'Oq', en: 'White' },
  'красный': { uz: 'Qizil', en: 'Red' },
  'ассорти красный, жёлтый и зелёный': { uz: 'Qizil, sariq va yashil assorti', en: 'Assorted red, yellow and green' },
  'очищенный': { uz: 'Tozalangan', en: 'Peeled' },
  'резаный': { uz: 'To‘g‘ralgan', en: 'Shredded' },
  'сливочное масло': { uz: 'Sariyog‘', en: 'Butter' },
  'сыр ломтиками': { uz: 'Bo‘laklangan pishloq', en: 'Cheese slices' },
  'сливочный сыр': { uz: 'Qaymoqli pishloq', en: 'Cream cheese' },
  'сыр': { uz: 'Pishloq', en: 'Cheese' },
  'сыр с голубой плесенью': { uz: 'Ko‘k mog‘orli pishloq', en: 'Blue cheese' },
  'мягкий сыр': { uz: 'Yumshoq pishloq', en: 'Soft cheese' },
  'фритюрное масло': { uz: 'Fritür moyi', en: 'Frying oil' },
  'Дани Нан': { uz: 'Dani Nan', en: 'Dani Nan' },
  'Алтын Нан': { uz: 'Oltin Nan', en: 'Altyn Nan' },
  'Мутабар': { uz: 'Mo‘tabar', en: 'Mutabar' },
  'Олейна': { uz: 'Oleyna', en: 'Oleyna' },
  'Салтанат': { uz: 'Saltanat', en: 'Saltanat' },
  'Ризамат': { uz: 'Rizamat', en: 'Rizamat' },
  'Рава': { uz: 'Rava', en: 'Rava' },
  'Орзу': { uz: 'Orzu', en: 'Orzu' },
};

const salesUnitLabels: Record<QuantityUnit, Record<Language, string>> = {
  piece: { ru: 'штука', uz: 'dona', en: 'piece' },
  gram: { ru: 'грамм', uz: 'gramm', en: 'gram' },
  kilogram: { ru: 'килограмм', uz: 'kilogramm', en: 'kilogram' },
  milliliter: { ru: 'миллилитр', uz: 'millilitr', en: 'millilitre' },
  liter: { ru: 'литр', uz: 'litr', en: 'litre' },
  meter: { ru: 'метр', uz: 'metr', en: 'metre' },
  square_meter: { ru: 'квадратный метр', uz: 'kvadrat metr', en: 'square metre' },
  pack: { ru: 'упаковка', uz: 'qadoq', en: 'pack' },
  roll: { ru: 'рулон', uz: 'rulon', en: 'roll' },
  box: { ru: 'коробка', uz: 'quti', en: 'box' },
  set: { ru: 'набор', uz: 'to‘plam', en: 'set' },
  service: { ru: 'услуга', uz: 'xizmat', en: 'service' },
  custom: { ru: 'единица', uz: 'birlik', en: 'unit' },
};

export function getSeedProductTranslation(code: string) {
  return productTranslations[code];
}

export function getLocalizedSalesUnitLabel(unitCode: QuantityUnit | undefined, language: Language) {
  return unitCode ? salesUnitLabels[unitCode]?.[language] : undefined;
}

function localizeMeasurements(value: string, language: Exclude<Language, 'ru'>) {
  const replacements = language === 'uz'
    ? [
      [/(?<!\p{L})шт\.(?!\p{L})/giu, 'dona'],
      [/(?<!\p{L})см(?!\p{L})/giu, 'sm'], [/(?<!\p{L})кг(?!\p{L})/giu, 'kg'], [/(?<!\p{L})мл(?!\p{L})/giu, 'ml'],
      [/(?<!\p{L})л(?!\p{L})/giu, 'l'], [/(?<!\p{L})г(?!\p{L})/giu, 'g'], [/(?<!\p{L})шт(?!\p{L})/giu, 'dona'],
      [/(?<!\p{L})м(?!\p{L})/giu, 'm'],
    ] as const
    : [
      [/(?<!\p{L})шт\.(?!\p{L})/giu, 'pcs'],
      [/(?<!\p{L})см(?!\p{L})/giu, 'cm'], [/(?<!\p{L})кг(?!\p{L})/giu, 'kg'], [/(?<!\p{L})мл(?!\p{L})/giu, 'ml'],
      [/(?<!\p{L})л(?!\p{L})/giu, 'L'], [/(?<!\p{L})г(?!\p{L})/giu, 'g'], [/(?<!\p{L})шт(?!\p{L})/giu, 'pcs'],
      [/(?<!\p{L})м(?!\p{L})/giu, 'm'],
    ] as const;

  return replacements.reduce((result, [pattern, replacement]) => result.replace(pattern, replacement), value);
}

export function localizeSeedAttributeValue(value: string, language: Language) {
  const trimmed = value.trim();
  if (language === 'ru' || !trimmed) return trimmed;
  return attributeValueTranslations[trimmed]?.[language] || localizeMeasurements(trimmed, language);
}

export function localizeSeedVariantLabel(value: string, language: Language) {
  if (language === 'ru') return value;
  return localizeMeasurements(value, language);
}
