import type { Language, QuantityUnit } from '@/types';

interface SeedProductTranslation {
  uz: string;
  en: string;
}

const chineseTitleReplacements: Array<[RegExp, string]> = [
  [/Extra-strong perforated bags/gi, '超强点断式连卷袋'],
  [/Extra-strong T-shirt bags/gi, '超强背心袋'],
  [/Refuse bags|Refuse sacks/gi, '垃圾袋'],
  [/Universal pizza bags/gi, '通用披萨袋'],
  [/Vacuum bags/gi, '真空袋'],
  [/Large stretch film/gi, '大卷保鲜膜'],
  [/Small stretch film/gi, '小卷保鲜膜'],
  [/Large aluminium foil/gi, '大卷铝箔'],
  [/Baking paper/gi, '烘焙纸'],
  [/Universal polyethylene gloves/gi, '通用聚乙烯手套'],
  [/yellow heavy-duty washing-up gloves/gi, '黄色加厚洗碗手套'],
  [/yellow rubber gloves/gi, '黄色橡胶手套'],
  [/black rubber gloves/gi, '黑色橡胶手套'],
  [/cleaning cloth/gi, '清洁布'],
  [/Dishwashing sponges/gi, '洗碗海绵'],
  [/Coloured table cloths/gi, '彩色桌面清洁布'],
  [/Korean cleaning sponge/gi, '韩式清洁海绵'],
  [/Microfibre floor cloth/gi, '超细纤维地布'],
  [/Two-ply roll towels/gi, '双层卷纸'],
  [/V-fold napkins/gi, 'V 折餐巾纸'],
  [/Z-fold napkins/gi, 'Z 折餐巾纸'],
  [/Square napkins/gi, '方形餐巾纸'],
  [/napkins/gi, '餐巾纸'],
  [/Two-ply toilet paper/gi, '双层卫生纸'],
  [/Wet wipes/gi, '湿巾'],
  [/Beef tenderloin/gi, '牛里脊'],
  [/Untrimmed beef tenderloin/gi, '未修整牛里脊'],
  [/Beef striploin/gi, '牛外脊'],
  [/Beef eye of round/gi, '牛后腿肉'],
  [/Beef outside round/gi, '牛后腿外侧肉'],
  [/Beef neck/gi, '牛颈肉'],
  [/Beef knuckle/gi, '牛腿芯肉'],
  [/Beef fat/gi, '牛脂'],
  [/Beef flank/gi, '牛腹肉'],
  [/Beef plate/gi, '牛胸腹肉'],
  [/Beef ribs/gi, '牛肋排'],
  [/Beef stew meat/gi, '炖煮牛肉'],
  [/Trimmed chicken breast/gi, '修整鸡胸肉'],
  [/Chicken breast/gi, '鸡胸肉'],
  [/Boneless skinless chicken thigh/gi, '去骨去皮鸡腿肉'],
  [/Boneless chicken thigh/gi, '去骨鸡腿肉'],
  [/Chicken thigh/gi, '鸡腿肉'],
  [/Chicken drumstick/gi, '鸡小腿'],
  [/Chicken leg quarter/gi, '鸡全腿'],
  [/Chicken wings/gi, '鸡翅'],
  [/Whole chicken/gi, '整鸡'],
  [/Chicken egg/gi, '鸡蛋'],
  [/premium flour/gi, '特级面粉'],
  [/first-grade flour/gi, '一级面粉'],
  [/Russian sugar/gi, '俄罗斯白糖'],
  [/ rice\b/gi, ' 大米'],
  [/Buckwheat/gi, '荞麦'],
  [/Lentils/gi, '扁豆'],
  [/American chickpeas/gi, '美国鹰嘴豆'],
  [/Iranian chickpeas/gi, '伊朗鹰嘴豆'],
  [/sunflower oil/gi, '葵花籽油'],
  [/Large Egyptian orange/gi, '埃及大橙'],
  [/Small Egyptian orange/gi, '埃及小橙'],
  [/Argentinian lemon/gi, '阿根廷柠檬'],
  [/Chilean kiwi/gi, '智利猕猴桃'],
  [/African grapefruit/gi, '非洲西柚'],
  [/Ecuadorian banana/gi, '厄瓜多尔香蕉'],
  [/Smooth-skinned avocado/gi, '光皮牛油果'],
  [/Hass avocado/gi, '哈斯牛油果'],
  [/Pineapple \(China\)/gi, '中国菠萝'],
  [/Lemon \(China\)/gi, '中国柠檬'],
  [/Local lemon/gi, '本地柠檬'],
  [/Lime/gi, '青柠'],
  [/Kiwi \(China\)/gi, '中国猕猴桃'],
  [/Passion fruit \(China\)/gi, '中国百香果'],
  [/Passion fruit \(Thailand\)/gi, '泰国百香果'],
  [/Yellow mini mango/gi, '黄小芒果'],
  [/Mango \(Peru\)/gi, '秘鲁芒果'],
  [/White peach/gi, '白桃'],
  [/Granny Smith apple/gi, '青苹果'],
  [/Saltanat apple/gi, 'Saltanat 苹果'],
  [/Shine Muscat grapes/gi, '阳光玫瑰葡萄'],
  [/Rizamat grapes/gi, 'Rizamat 葡萄'],
  [/Blueberries/gi, '蓝莓'],
  [/Blackberries/gi, '黑莓'],
  [/Blackcurrants/gi, '黑加仑'],
  [/Physalis/gi, '灯笼果'],
  [/Raspberries/gi, '树莓'],
  [/Strawberries/gi, '草莓'],
  [/Chinese cabbage/gi, '大白菜'],
  [/Carrots/gi, '胡萝卜'],
  [/Onions/gi, '洋葱'],
  [/Potatoes/gi, '土豆'],
  [/Pink Paradise tomato/gi, 'Pink Paradise 番茄'],
  [/Red tomato/gi, '红番茄'],
  [/Rava cucumbers/gi, 'Rava 黄瓜'],
  [/Orzu cucumbers/gi, 'Orzu 黄瓜'],
  [/Ginger/gi, '生姜'],
  [/Traffic Light sweet peppers/gi, '彩椒'],
  [/Peeled garlic/gi, '去皮大蒜'],
  [/Button mushrooms/gi, '双孢蘑菇'],
  [/Asparagus/gi, '芦笋'],
  [/iceberg lettuce/gi, '冰山生菜'],
  [/romaine lettuce/gi, '罗马生菜'],
  [/lettuce/gi, '生菜'],
  [/rocket/gi, '芝麻菜'],
  [/spinach/gi, '菠菜'],
  [/kale/gi, '羽衣甘蓝'],
  [/chard/gi, '瑞士甜菜'],
  [/celery stalk/gi, '西芹杆'],
  [/rosemary/gi, '迷迭香'],
  [/mint/gi, '薄荷'],
  [/coriander/gi, '香菜'],
  [/dill/gi, '莳萝'],
  [/Dutch parsley/gi, '荷兰欧芹'],
  [/parsley/gi, '欧芹'],
  [/spring onions/gi, '小葱'],
  [/radishes/gi, '小萝卜'],
  [/celery/gi, '芹菜'],
  [/shredded/gi, '切丝'],
  [/microgreens/gi, '微型蔬菜'],
  [/amaranth/gi, '苋菜'],
  [/broccoli/gi, '西兰花'],
  [/pea shoots/gi, '豌豆苗'],
  [/mustard/gi, '芥菜'],
  [/daikon/gi, '白萝卜'],
  [/red radish/gi, '红萝卜'],
  [/cress/gi, '水田芥'],
  [/sorrel/gi, '酸模'],
  [/edible flowers/gi, '食用花'],
  [/butter/gi, '黄油'],
  [/cream cheese/gi, '奶油奶酪'],
  [/Cheese Burger cheese/gi, '汉堡芝士片'],
  [/Creamy cheese/gi, '奶油芝士片'],
  [/cheese/gi, '奶酪'],
  [/frying oil/gi, '炸油'],
];

function translateSeedTitleToChinese(value: string) {
  const translated = chineseTitleReplacements.reduce(
    (result, [pattern, replacement]) => result.replace(pattern, replacement),
    value,
  );
  return translated
    .replace(/(\d(?:[\d.,–/-]*\d)?)\s*cm\b/gi, '$1 厘米')
    .replace(/(\d(?:[\d.,–/-]*\d)?)\s*kg\b/gi, '$1 千克')
    .replace(/(\d(?:[\d.,–/-]*\d)?)\s*g\b/gi, '$1 克')
    .replace(/(\d(?:[\d.,–/-]*\d)?)\s*L\b/g, '$1 升')
    .replace(/(\d+)\s*pcs?\b/gi, '$1 件')
    .replace(/(\d+)\s*slices?\b/gi, '$1 片')
    .replace(/(\d+)\s*rolls?\b/gi, '$1 卷')
    .replace(/(\d(?:[\d.,–/-]*\d)?)\s*m\b/gi, '$1 米')
    .replace(/block of\s*(\d+)/gi, '$1 件装')
    .replace(/,\s*/g, '，')
    .replace(/\s+/g, ' ')
    .trim();
}

const productTranslations: Record<string, SeedProductTranslation> = {
  'TB-001': { uz: 'Chiqindi paketlari 45×50 sm, 20 l, 40 dona', en: 'Refuse bags 45×50 cm, 20 L, 40 pcs' },
  'TB-002': { uz: 'Chiqindi paketlari 45×60 sm, 22 l, 30 dona', en: 'Refuse bags 45×60 cm, 22 L, 30 pcs' },
  'TB-003': { uz: 'Chiqindi paketlari 50×70 sm, 41 l, 25 dona', en: 'Refuse bags 50×70 cm, 41 L, 25 pcs' },
  'TB-004': { uz: 'Chiqindi paketlari 60×90 sm, 85 l, 9 dona', en: 'Refuse bags 60×90 cm, 85 L, 9 pcs' },
  'TB-005': { uz: 'Chiqindi paketlari 80×110 sm, 160 l, 7 dona', en: 'Refuse bags 80×110 cm, 160 L, 7 pcs' },
  'TB-006': { uz: 'Chiqindi qoplari 90×110 sm, 200 l, 7 dona', en: 'Refuse sacks 90×110 cm, 200 L, 7 pcs' },
  'TB-007': { uz: 'Chiqindi paketlari 90×120 sm, 240 l, 6 dona', en: 'Refuse bags 90×120 cm, 240 L, 6 pcs' },
  'TB-008': { uz: 'Chiqindi paketlari 90×120 sm, 240 l, 11 dona', en: 'Refuse bags 90×120 cm, 240 L, 11 pcs' },
  'TO-001': { uz: 'Uziladigan o‘ta mustahkam paketlar 19×27 sm, 222 dona', en: 'Extra-strong perforated bags 19×27 cm, 222 pcs' },
  'TO-002': { uz: 'Uziladigan o‘ta mustahkam paketlar 28×38 sm, 303 dona', en: 'Extra-strong perforated bags 28×38 cm, 303 pcs' },
  'CB-001': { uz: '«Mayka» paketlari 3 kg, o‘ta mustahkam, 50 dona', en: 'Extra-strong T-shirt bags, 3 kg, 50 pcs' },
  'CB-002': { uz: '«Mayka» paketlari 5 kg, o‘ta mustahkam, 50 dona', en: 'Extra-strong T-shirt bags, 5 kg, 50 pcs' },
  'CB-003': { uz: '«Mayka» paketlari 10 kg, o‘ta mustahkam, 30 dona', en: 'Extra-strong T-shirt bags, 10 kg, 30 pcs' },
  'CB-004': { uz: '«Mayka» paketlari 25 kg, o‘ta mustahkam, 25 dona', en: 'Extra-strong T-shirt bags, 25 kg, 25 pcs' },
  'CB-005': { uz: '«Mayka» paketlari 50 kg, o‘ta mustahkam, 25 dona', en: 'Extra-strong T-shirt bags, 50 kg, 25 pcs' },
  'VB-001': { uz: 'Vakuum paketlari 15×25 sm', en: 'Vacuum bags 15×25 cm' },
  'VB-002': { uz: 'Vakuum paketlari 20×25 sm', en: 'Vacuum bags 20×25 cm' },
  'VB-003': { uz: 'Vakuum paketlari 25×35 sm', en: 'Vacuum bags 25×35 cm' },
  'PB-001': { uz: 'Universal pitsa paketlari 25/30/35 sm, 40 dona', en: 'Universal pizza bags 25/30/35 cm, 40 pcs' },
  'FP-001': { uz: 'Katta streych plyonka, 45 sm', en: 'Large stretch film, 45 cm' },
  'FP-002': { uz: 'Kichik streych plyonka, 30 sm', en: 'Small stretch film, 30 cm' },
  'FP-003': { uz: 'Katta folga, 2 kg, 45 sm', en: 'Large aluminium foil, 2 kg, 45 cm' },
  'FP-004': { uz: 'Pishirish qog‘ozi 37 sm × 40 m', en: 'Baking paper 37 cm × 40 m' },
  'GL-001': { uz: 'Universal polietilen qo‘lqoplar, 100 dona', en: 'Universal polyethylene gloves, 100 pcs' },
  'GL-002': { uz: 'Mikky sariq rezina qo‘lqoplari L, 2 dona', en: 'Mikky yellow rubber gloves, size L, 2 pcs' },
  'GL-003': { uz: 'Mikky sariq qalin idish yuvish qo‘lqoplari L, 2 dona', en: 'Mikky yellow heavy-duty washing-up gloves, size L, 2 pcs' },
  'GL-004': { uz: 'Touch Flex qora rezina qo‘lqoplari XL/L/M, 100 dona', en: 'Touch Flex black rubber gloves XL/L/M, 100 pcs' },
  'CL-001': { uz: '«Delfin» tozalash lattasi, 1 dona', en: 'Dolphin cleaning cloth, 1 pc' },
  'CL-002': { uz: 'Idish yuvish gubkalari, 3 dona', en: 'Dishwashing sponges, 3 pcs' },
  'CL-003': { uz: 'Stol uchun rangli lattalar, 3 dona', en: 'Coloured table cloths, 3 pcs' },
  'CL-004': { uz: 'Koreys gubkasi, 1 dona', en: 'Korean cleaning sponge, 1 pc' },
  'CL-005': { uz: 'Mikrofibrali pol lattasi', en: 'Microfibre floor cloth' },
  'PG-001': { uz: 'Rulonli salfetkalar, 2 qatlamli, 2 rulon', en: 'Two-ply roll towels, 2 rolls' },
  'PG-002': { uz: 'V shaklidagi salfetkalar 19,5×10,5 sm, 150 dona', en: 'V-fold napkins 19.5×10.5 cm, 150 pcs' },
  'PG-003': { uz: 'Z shaklidagi salfetkalar, 180 dona', en: 'Z-fold napkins, 180 pcs' },
  'PG-004': { uz: 'Kvadrat salfetkalar 23×23 sm, 100 dona', en: 'Square napkins 23×23 cm, 100 pcs' },
  'PG-005': { uz: 'Longper Premium salfetkalari, 40 dona', en: 'Longper Premium napkins, 40 pcs' },
  'PG-006': { uz: 'Ikki qatlamli tualet qog‘ozi, 6 rulon', en: 'Two-ply toilet paper, 6 rolls' },
  'PG-007': { uz: 'Nam salfetkalar, 300 donali blok', en: 'Wet wipes, block of 300' },

  'BF-001': { uz: 'Bon-file', en: 'Beef tenderloin' },
  'BF-002': { uz: 'Tozalanmagan bon-file', en: 'Untrimmed beef tenderloin' },
  'BF-003': { uz: 'Kontr-file', en: 'Beef striploin' },
  'BF-004': { uz: 'Mol go‘shti kachalkasi', en: 'Beef eye of round' },
  'BF-005': { uz: 'Mol bo‘yni', en: 'Beef neck' },
  'BF-006': { uz: 'Mol go‘shti tranchi', en: 'Beef knuckle' },
  'BF-007': { uz: 'Tashqi son go‘shti', en: 'Beef outside round' },
  'BF-008': { uz: 'Mol charvisi', en: 'Beef fat' },
  'BF-009': { uz: 'Mol go‘shti shapogi (pashina)', en: 'Beef flank' },
  'BF-010': { uz: 'Sarpanja', en: 'Beef plate' },
  'BF-011': { uz: 'Mol qovurg‘asi', en: 'Beef ribs' },
  'BF-012': { uz: 'Mol go‘shtli ragu', en: 'Beef stew meat' },
  'CH-001': { uz: 'Tovuq ko‘krak go‘shti', en: 'Chicken breast' },
  'CH-002': { uz: 'Tozalangan tovuq ko‘krak go‘shti', en: 'Trimmed chicken breast' },
  'CH-003': { uz: 'Tovuq soni', en: 'Chicken thigh' },
  'CH-004': { uz: 'Suyaksiz tovuq soni', en: 'Boneless chicken thigh' },
  'CH-005': { uz: 'Suyaksiz va terisiz tovuq soni', en: 'Boneless skinless chicken thigh' },
  'CH-006': { uz: 'Tovuq boldiri', en: 'Chicken drumstick' },
  'CH-007': { uz: 'Tovuq son go‘shti', en: 'Chicken leg quarter' },
  'CH-008': { uz: 'Tovuq qanotlari', en: 'Chicken wings' },
  'CH-009': { uz: 'Butun tovuq, 2–2,5 kg', en: 'Whole chicken, 2–2.5 kg' },
  'EG-001': { uz: 'Tovuq tuxumi', en: 'Chicken egg' },

  'FL-001': { uz: '«Dani Nan» oliy navli un, 50 kg', en: 'Dani Nan premium flour, 50 kg' },
  'FL-002': { uz: '«Dani Nan» oliy navli un, 25 kg', en: 'Dani Nan premium flour, 25 kg' },
  'FL-003': { uz: '«Dani Nan» 1-navli un, 50 kg', en: 'Dani Nan first-grade flour, 50 kg' },
  'FL-004': { uz: '«Dani Nan» 1-navli un, 25 kg', en: 'Dani Nan first-grade flour, 25 kg' },
  'FL-005': { uz: '«Oltin Nan» oliy navli un, 50 kg', en: 'Altyn Nan premium flour, 50 kg' },
  'FL-006': { uz: '«Oltin Nan» 1-navli un, 50 kg', en: 'Altyn Nan first-grade flour, 50 kg' },
  'FL-007': { uz: '«Mo‘tabar» oliy navli un, 50 kg', en: 'Mutabar premium flour, 50 kg' },
  'FL-008': { uz: '«Mo‘tabar» 1-navli un, 50 kg', en: 'Mutabar first-grade flour, 50 kg' },
  'SG-001': { uz: 'Rossiya shakari, 50 kg', en: 'Russian sugar, 50 kg' },
  'GR-001': { uz: '«Lazer» guruchi', en: 'Lazer rice' },
  'GR-002': { uz: '«Alanga» guruchi', en: 'Alanga rice' },
  'GR-003': { uz: 'Grechka', en: 'Buckwheat' },
  'GR-004': { uz: 'Yasmiq', en: 'Lentils' },
  'GR-005': { uz: 'Amerika no‘xati', en: 'American chickpeas' },
  'GR-006': { uz: 'Eron no‘xati', en: 'Iranian chickpeas' },
  'OI-001': { uz: '«Oleyna» kungaboqar moyi, 5 l', en: 'Oleyna sunflower oil, 5 L' },

  'FR-001': { uz: 'Yirik Misr apelsini', en: 'Large Egyptian orange' },
  'FR-002': { uz: 'Mayda Misr apelsini', en: 'Small Egyptian orange' },
  'FR-003': { uz: 'Argentina limoni', en: 'Argentinian lemon' },
  'FR-004': { uz: 'Chili kivisi', en: 'Chilean kiwi' },
  'FR-005': { uz: 'Afrika greypfruti', en: 'African grapefruit' },
  'FR-006': { uz: 'Ekvador banani', en: 'Ecuadorian banana' },
  'FR-007': { uz: 'Silliq avokado', en: 'Smooth-skinned avocado' },
  'FR-008': { uz: 'Hass avokadosi', en: 'Hass avocado' },
  'FR-009': { uz: 'Ananas (Xitoy)', en: 'Pineapple (China)' },
  'FR-010': { uz: 'Limon (Xitoy)', en: 'Lemon (China)' },
  'FR-011': { uz: 'Mahalliy limon', en: 'Local lemon' },
  'FR-012': { uz: 'Laym', en: 'Lime' },
  'FR-013': { uz: 'Kivi (Xitoy)', en: 'Kiwi (China)' },
  'FR-014': { uz: 'Marakuya (Xitoy)', en: 'Passion fruit (China)' },
  'FR-015': { uz: 'Marakuya (Tailand)', en: 'Passion fruit (Thailand)' },
  'FR-016': { uz: 'Sariq mini mango', en: 'Yellow mini mango' },
  'FR-017': { uz: 'Mango (Peru)', en: 'Mango (Peru)' },
  'FR-018': { uz: 'Oq shaftoli', en: 'White peach' },
  'FR-019': { uz: 'Granny Smith olmasi', en: 'Granny Smith apple' },
  'FR-020': { uz: 'Saltanat olmasi', en: 'Saltanat apple' },
  'FR-021': { uz: 'Shine Muscat uzumi', en: 'Shine Muscat grapes' },
  'FR-022': { uz: 'Rizamat uzumi', en: 'Rizamat grapes' },
  'BR-001': { uz: 'Golubika, 500 g', en: 'Blueberries, 500 g' },
  'BR-002': { uz: 'Golubika, 125 g', en: 'Blueberries, 125 g' },
  'BR-003': { uz: 'Maymunjon, 125 g', en: 'Blackberries, 125 g' },
  'BR-004': { uz: 'Qoraqat, 125 g', en: 'Blackcurrants, 125 g' },
  'BR-005': { uz: 'Fizalis, 125 g', en: 'Physalis, 125 g' },
  'BR-006': { uz: 'Malina, 125 g', en: 'Raspberries, 125 g' },
  'BR-007': { uz: 'Qulupnay', en: 'Strawberries' },
  'VG-001': { uz: 'Pekin karami', en: 'Chinese cabbage' },
  'VG-002': { uz: 'Sabzi', en: 'Carrots' },
  'VG-003': { uz: 'Bosh piyoz', en: 'Onions' },
  'VG-004': { uz: 'Kartoshka', en: 'Potatoes' },
  'VG-005': { uz: 'Pink Paradise pomidori', en: 'Pink Paradise tomato' },
  'VG-006': { uz: 'Qizil pomidor', en: 'Red tomato' },
  'VG-007': { uz: 'Rava bodringi', en: 'Rava cucumbers' },
  'VG-008': { uz: 'Orzu bodringi', en: 'Orzu cucumbers' },
  'VG-009': { uz: 'Zanjabil', en: 'Ginger' },
  'VG-010': { uz: '«Svetofor» bulg‘or qalampiri', en: 'Traffic Light sweet peppers' },
  'VG-011': { uz: 'Tozalangan sarimsoq', en: 'Peeled garlic' },
  'VG-012': { uz: 'Shampinyonlar', en: 'Button mushrooms' },
  'VG-013': { uz: 'Sarsabil', en: 'Asparagus' },

  'GN-001': { uz: 'Novagreen Aysberg salati, 500 g', en: 'Novagreen iceberg lettuce, 500 g' },
  'GN-002': { uz: 'Novagreen latuk salati, 500 g', en: 'Novagreen lettuce, 500 g' },
  'GN-003': { uz: 'Novagreen Romano salati, 500 g', en: 'Novagreen romaine lettuce, 500 g' },
  'GN-004': { uz: 'Novagreen rukkolasi', en: 'Novagreen rocket' },
  'GN-006': { uz: 'Novagreen ismaloqi', en: 'Novagreen spinach' },
  'GN-008': { uz: 'Novagreen Lollo Rosso salati, 500 g', en: 'Novagreen Lollo Rosso lettuce, 500 g' },
  'GN-009': { uz: 'Novagreen keyli, 500 g', en: 'Novagreen kale, 500 g' },
  'GN-010': { uz: 'Novagreen mangoldi', en: 'Novagreen chard' },
  'GN-012': { uz: 'Novagreen selderey poyasi, 1 dona', en: 'Novagreen celery stalk, 1 pc' },
  'GN-013': { uz: 'Novagreen rozmarini', en: 'Novagreen rosemary' },
  'GN-016': { uz: 'Novagreen yalpizi', en: 'Novagreen mint' },
  'GN-018': { uz: 'Novagreen kashnichi', en: 'Novagreen coriander' },
  'GN-020': { uz: 'Novagreen ukropi', en: 'Novagreen dill' },
  'GN-022': { uz: 'Novagreen golland petrushkasi', en: 'Novagreen Dutch parsley' },
  'GN-024': { uz: 'Novagreen petrushkasi, 500 g', en: 'Novagreen parsley, 500 g' },
  'GN-025': { uz: 'Novagreen qo‘zichoq piyozi, 500 g', en: 'Novagreen lamb onion, 500 g' },
  'GN-026': { uz: 'Novagreen ko‘k piyozi, 500 g', en: 'Novagreen spring onions, 500 g' },
  'GN-027': { uz: 'Novagreen rediskasi, 500 g', en: 'Novagreen radishes, 500 g' },
  'GN-028': { uz: 'Novagreen seldereyi, 500 g', en: 'Novagreen celery, 500 g' },
  'GN-029': { uz: 'Novagreen to‘g‘ralgan Aysberg salati, 500 g', en: 'Novagreen shredded iceberg lettuce, 500 g' },
  'MG-001': { uz: 'Novagreen amarant mikroko‘kati, 1 dona', en: 'Novagreen amaranth microgreens, 1 pc' },
  'MG-002': { uz: 'Novagreen brokkoli mikroko‘kati, 1 dona', en: 'Novagreen broccoli microgreens, 1 pc' },
  'MG-003': { uz: 'Novagreen no‘xat mikroko‘kati, 1 dona', en: 'Novagreen pea shoots, 1 pc' },
  'MG-004': { uz: 'Novagreen xantal mikroko‘kati, 1 dona', en: 'Novagreen mustard microgreens, 1 pc' },
  'MG-005': { uz: 'Novagreen daykon mikroko‘kati, 1 dona', en: 'Novagreen daikon microgreens, 1 pc' },
  'MG-006': { uz: 'Novagreen qizil rediska mikroko‘kati, 1 dona', en: 'Novagreen red radish microgreens, 1 pc' },
  'MG-007': { uz: 'Novagreen kress-salat mikroko‘kati, 1 dona', en: 'Novagreen cress microgreens, 1 pc' },
  'MG-008': { uz: 'Novagreen latuk mikroko‘kati, 1 dona', en: 'Novagreen lettuce microgreens, 1 pc' },
  'MG-009': { uz: 'Novagreen rediska mikroko‘kati, 1 dona', en: 'Novagreen radish microgreens, 1 pc' },
  'MG-010': { uz: 'Novagreen rukkola mikroko‘kati, 1 dona', en: 'Novagreen rocket microgreens, 1 pc' },
  'MG-011': { uz: 'Novagreen «Yeyiladigan gullar» mikroko‘kati, 1 dona', en: 'Novagreen edible flowers, 1 pc' },
  'MG-012': { uz: 'Novagreen shovul mikroko‘kati, 1 dona', en: 'Novagreen sorrel microgreens, 1 pc' },

  'DA-001': { uz: 'Fin sariyog‘i, 500 g', en: 'Fin butter, 500 g' },
  'DA-002': { uz: 'Valio sariyog‘i, 1 kg', en: 'Valio butter, 1 kg' },
  'DA-003': { uz: 'Valio sariyog‘i, 500 g', en: 'Valio butter, 500 g' },
  'DA-004': { uz: 'Svalya sariyog‘i', en: 'Svalya butter' },
  'DA-006': { uz: 'Viola Cheese Burger pishlog‘i, 8 bo‘lak', en: 'Viola Cheese Burger cheese, 8 slices' },
  'DA-007': { uz: 'Viola Creamy pishlog‘i, 8 bo‘lak', en: 'Viola Creamy cheese, 8 slices' },
  'DA-008': { uz: 'Viola qaymoqli pishlog‘i, 400 g', en: 'Viola cream cheese, 400 g' },
  'DA-009': { uz: 'Fitaki pishlog‘i, 500 g', en: 'Fitaki cheese, 500 g' },
  'DA-010': { uz: 'Dor Blue pishlog‘i, 2,5 kg', en: 'Dor Blue cheese, 2.5 kg' },
  'DA-011': { uz: 'Camembert pishlog‘i, 500 g', en: 'Camembert cheese, 500 g' },
  'DA-012': { uz: 'Brie pishlog‘i, 500 g', en: 'Brie cheese, 500 g' },
  'DA-013': { uz: 'Svalya pishlog‘i, 3 kg', en: 'Svalya cheese, 3 kg' },
  'OI-002': { uz: 'Unity fritür moyi, 10 l', en: 'Unity frying oil, 10 L' },
};

const attributeValueTranslations: Record<string, SeedProductTranslation> = {
  'полиэтиленовые': { uz: 'Polietilen', en: 'Polyethylene' },
  'резиновые': { uz: 'Rezina', en: 'Rubber' },
  'резиновые утолщённые': { uz: 'Qalin rezina', en: 'Heavy-duty rubber' },
  '2 слоя': { uz: '2 qatlam', en: '2 ply' },
  'говядина': { uz: 'Mol go‘shti', en: 'Beef' },
  'курица': { uz: 'Tovuq go‘shti', en: 'Chicken' },
  'высший сорт': { uz: 'Oliy nav', en: 'Premium grade' },
  '1 сорт': { uz: '1-nav', en: 'First grade' },
  'Россия': { uz: 'Rossiya', en: 'Russia' },
  'США': { uz: 'AQSH', en: 'United States' },
  'Иран': { uz: 'Eron', en: 'Iran' },
  'рис': { uz: 'Guruch', en: 'Rice' },
  'Египет': { uz: 'Misr', en: 'Egypt' },
  'Аргентина': { uz: 'Argentina', en: 'Argentina' },
  'Чили': { uz: 'Chili', en: 'Chile' },
  'Африка': { uz: 'Afrika', en: 'Africa' },
  'Эквадор': { uz: 'Ekvador', en: 'Ecuador' },
  'Китай': { uz: 'Xitoy', en: 'China' },
  'Узбекистан': { uz: 'O‘zbekiston', en: 'Uzbekistan' },
  'Таиланд': { uz: 'Tailand', en: 'Thailand' },
  'Перу': { uz: 'Peru', en: 'Peru' },
  'крупный': { uz: 'Yirik', en: 'Large' },
  'мелкий': { uz: 'Mayda', en: 'Small' },
  'гладкий': { uz: 'Silliq po‘stli', en: 'Smooth-skinned' },
  'жёлтый мини': { uz: 'Sariq mini', en: 'Yellow mini' },
  'белый': { uz: 'Oq', en: 'White' },
  'красный': { uz: 'Qizil', en: 'Red' },
  'ассорти красный, жёлтый и зелёный': { uz: 'Qizil, sariq va yashil assorti', en: 'Assorted red, yellow and green' },
  'очищенный': { uz: 'Tozalangan', en: 'Peeled' },
  'резаный': { uz: 'To‘g‘ralgan', en: 'Shredded' },
  'сливочное масло': { uz: 'Sariyog‘', en: 'Butter' },
  'сыр ломтиками': { uz: 'Bo‘laklangan pishloq', en: 'Cheese slices' },
  'сливочный сыр': { uz: 'Qaymoqli pishloq', en: 'Cream cheese' },
  'сыр': { uz: 'Pishloq', en: 'Cheese' },
  'сыр с голубой плесенью': { uz: 'Ko‘k mog‘orli pishloq', en: 'Blue cheese' },
  'мягкий сыр': { uz: 'Yumshoq pishloq', en: 'Soft cheese' },
  'фритюрное масло': { uz: 'Fritür moyi', en: 'Frying oil' },
  'Дани Нан': { uz: 'Dani Nan', en: 'Dani Nan' },
  'Алтын Нан': { uz: 'Oltin Nan', en: 'Altyn Nan' },
  'Мутабар': { uz: 'Mo‘tabar', en: 'Mutabar' },
  'Олейна': { uz: 'Oleyna', en: 'Oleyna' },
  'Салтанат': { uz: 'Saltanat', en: 'Saltanat' },
  'Ризамат': { uz: 'Rizamat', en: 'Rizamat' },
  'Рава': { uz: 'Rava', en: 'Rava' },
  'Орзу': { uz: 'Orzu', en: 'Orzu' },
};

const salesUnitLabels: Record<QuantityUnit, Record<Exclude<Language, 'zh'>, string>> = {
  piece: { ru: 'штука', uz: 'dona', en: 'piece' },
  gram: { ru: 'грамм', uz: 'gramm', en: 'gram' },
  kilogram: { ru: 'килограмм', uz: 'kilogramm', en: 'kilogram' },
  milliliter: { ru: 'миллилитр', uz: 'millilitr', en: 'millilitre' },
  liter: { ru: 'литр', uz: 'litr', en: 'litre' },
  meter: { ru: 'метр', uz: 'metr', en: 'metre' },
  square_meter: { ru: 'квадратный метр', uz: 'kvadrat metr', en: 'square metre' },
  pack: { ru: 'упаковка', uz: 'qadoq', en: 'pack' },
  roll: { ru: 'рулон', uz: 'rulon', en: 'roll' },
  box: { ru: 'коробка', uz: 'quti', en: 'box' },
  set: { ru: 'набор', uz: 'to‘plam', en: 'set' },
  service: { ru: 'услуга', uz: 'xizmat', en: 'service' },
  custom: { ru: 'единица', uz: 'birlik', en: 'unit' },
};

const chineseSalesUnitLabels: Record<QuantityUnit, string> = {
  piece: '件', gram: '克', kilogram: '千克', milliliter: '毫升', liter: '升',
  meter: '米', square_meter: '平方米', pack: '包', roll: '卷', box: '箱',
  set: '套', service: '项服务', custom: '单位',
};

const chineseAttributeValues: Record<string, string> = {
  Polyethylene: '聚乙烯', Rubber: '橡胶', 'Heavy-duty rubber': '加厚橡胶', '2 ply': '双层',
  Beef: '牛肉', Chicken: '鸡肉', 'Premium grade': '特级', 'First grade': '一级',
  Russia: '俄罗斯', 'United States': '美国', Iran: '伊朗', Rice: '大米', Egypt: '埃及',
  Argentina: '阿根廷', Chile: '智利', Africa: '非洲', Ecuador: '厄瓜多尔', China: '中国',
  Uzbekistan: '乌兹别克斯坦', Thailand: '泰国', Peru: '秘鲁', Large: '大号', Small: '小号',
  'Smooth-skinned': '光皮', 'Yellow mini': '黄色迷你', White: '白色', Red: '红色',
  'Assorted red, yellow and green': '红黄绿混色', Peeled: '去皮', Shredded: '切丝',
  Butter: '黄油', 'Cheese slices': '芝士片', 'Cream cheese': '奶油奶酪', Cheese: '奶酪',
  'Blue cheese': '蓝纹奶酪', 'Soft cheese': '软质奶酪', 'Frying oil': '炸油',
};

export function getSeedProductTranslation(code: string) {
  const translation = productTranslations[code];
  return translation ? { ...translation, zh: translateSeedTitleToChinese(translation.en) } : undefined;
}

export function getLocalizedSalesUnitLabel(unitCode: QuantityUnit | undefined, language: Language) {
  if (!unitCode) return undefined;
  return language === 'zh' ? chineseSalesUnitLabels[unitCode] : salesUnitLabels[unitCode]?.[language];
}

function localizeMeasurements(value: string, language: Exclude<Language, 'ru'>) {
  const replacements = language === 'uz'
    ? [
      [/(?<!\p{L})шт\.(?!\p{L})/giu, 'dona'],
      [/(?<!\p{L})см(?!\p{L})/giu, 'sm'], [/(?<!\p{L})кг(?!\p{L})/giu, 'kg'], [/(?<!\p{L})мл(?!\p{L})/giu, 'ml'],
      [/(?<!\p{L})л(?!\p{L})/giu, 'l'], [/(?<!\p{L})г(?!\p{L})/giu, 'g'], [/(?<!\p{L})шт(?!\p{L})/giu, 'dona'],
      [/(?<!\p{L})м(?!\p{L})/giu, 'm'],
    ] as const
    : language === 'zh'
      ? [
        [/(?<!\p{L})шт\.(?!\p{L})/giu, '件'],
        [/(?<!\p{L})см(?!\p{L})/giu, '厘米'], [/(?<!\p{L})кг(?!\p{L})/giu, '千克'], [/(?<!\p{L})мл(?!\p{L})/giu, '毫升'],
        [/(?<!\p{L})л(?!\p{L})/giu, '升'], [/(?<!\p{L})г(?!\p{L})/giu, '克'], [/(?<!\p{L})шт(?!\p{L})/giu, '件'],
        [/(?<!\p{L})м(?!\p{L})/giu, '米'],
      ] as const
      : [
      [/(?<!\p{L})шт\.(?!\p{L})/giu, 'pcs'],
      [/(?<!\p{L})см(?!\p{L})/giu, 'cm'], [/(?<!\p{L})кг(?!\p{L})/giu, 'kg'], [/(?<!\p{L})мл(?!\p{L})/giu, 'ml'],
      [/(?<!\p{L})л(?!\p{L})/giu, 'L'], [/(?<!\p{L})г(?!\p{L})/giu, 'g'], [/(?<!\p{L})шт(?!\p{L})/giu, 'pcs'],
      [/(?<!\p{L})м(?!\p{L})/giu, 'm'],
    ] as const;

  return replacements.reduce((result, [pattern, replacement]) => result.replace(pattern, replacement), value);
}

export function localizeSeedAttributeValue(value: string, language: Language) {
  const trimmed = value.trim();
  if (language === 'ru' || !trimmed) return trimmed;
  if (language === 'zh') {
    const english = attributeValueTranslations[trimmed]?.en;
    return english ? chineseAttributeValues[english] || english : localizeMeasurements(trimmed, 'zh');
  }
  const contentLanguage = language;
  return attributeValueTranslations[trimmed]?.[contentLanguage] || localizeMeasurements(trimmed, contentLanguage);
}

export function localizeSeedVariantLabel(value: string, language: Language) {
  if (language === 'ru') return value;
  return localizeMeasurements(value, language);
}
