import { ClientPartner, Banner, SiteSettings } from '@/types';
import { priceList2026Attributes, priceList2026Categories, priceList2026Products } from '@/lib/catalog/sanpackPriceLists2026';

export const initialSiteSettings: SiteSettings = {
  company: {
    name: 'SANPACK',
    logo: '/logo-sanpack.svg',
    logoDark: '/logo-white.svg',
    favicon: '/favicon.ico',
    descriptionRu: 'Комплексный поставщик упаковки, расходных материалов и продуктов питания для HoReCa',
    descriptionUz: 'HoReCa uchun qadoqlash, sarf materiallari va oziq-ovqat mahsulotlarining kompleks yetkazib beruvchisi',
    descriptionEn: 'A full-service supplier of packaging, consumables and food products for HoReCa',
    descriptionZh: '面向 HoReCa 行业的包装、耗材和食品综合供应商',
  },
  contacts: {
    phone1: '+998 99 851 05 06',
    phone2: '+998 99 232 39 99',
    email: 'info@sanpack.uz',
    addressRu: 'г. Ташкент, Сергелийский р-н, ул. Янги Сергели, 14А',
    addressUz: 'Toshkent sh., Sergeli t-ni, Yangi Sergeli ko‘ch., 14A',
    addressEn: '14A Yangi Sergeli Street, Sergeli District, Tashkent',
    addressZh: '塔什干市谢尔盖利区扬吉谢尔盖利街 14A',
    workingHoursRu: 'Пн — Сб: 09:00 - 18:00',
    workingHoursUz: 'Du — Sha: 09:00 - 18:00',
    workingHoursEn: 'Mon — Sat: 09:00 - 18:00',
    workingHoursZh: '周一至周六：09:00–18:00',
    telegram: 'https://t.me/sanpack_uz',
    whatsapp: 'https://wa.me/998998510506',
    cityRu: 'Ташкент',
    cityUz: 'Toshkent',
    cityEn: 'Tashkent',
    cityZh: '塔什干',
  },
  salesMode: 'request_only',
  commerce: {
    currency: 'UZS',
    checkoutFields: {
      name: true,
      phone: true,
    },
  },
  locale: {
    defaultLanguage: 'ru',
    supportedLanguages: ['ru'],
  },
  design: {
    designVersion: 2,
    primaryColor: '#0F6E43',
    secondaryColor: '#DCE9AF',
    borderRadius: 14,
    themeMode: 'light',
    fontPair: 'modern',
  },
  seo: {
    defaultTitleRu: 'SANPACK — Упаковка, расходные материалы и продукты для HoReCa в Ташкенте',
    defaultTitleUz: 'SANPACK — Toshkentda HoReCa uchun qadoqlash, sarf materiallari va oziq-ovqat',
    defaultDescriptionRu: 'Производство и оптовые поставки мусорных мешков, пакетов, перчаток, фольги, стрейч-пленки, бакалеи и полиграфии для ресторанов, отелей и бизнеса.',
    defaultDescriptionUz: 'Restoranlar, mehmonxonalar va biznes uchun chiqindi qoplari, paketlar, qo‘lqoplar, folga, strech plyonka va oziq-ovqat mahsulotlarini ulgurji yetkazib berish.',
    defaultTitleEn: 'SANPACK — Packaging, consumables and HoReCa products in Tashkent',
    defaultTitleZh: 'SANPACK — 塔什干 HoReCa 包装、耗材与食品供应',
    defaultDescriptionEn: 'Production and wholesale supply of refuse bags, carrier bags, gloves, foil, stretch film, groceries and printing services for restaurants, hotels and businesses.',
    defaultDescriptionZh: '为餐厅、酒店和企业生产并批发垃圾袋、包装袋、手套、铝箔、保鲜膜、食品和印刷服务。',
  },
  modules: {
    branding: {
      enabled: true,
      navigationImage: '/catalog/category-icons-v3/branding-service-v2.webp',
    },
    bagDesigner: {
      enabled: true,
      navigationImage: '/catalog/category-icons-v3/bag-designer-service-v2.webp',
    },
  },
};

export const initialCategories = priceList2026Categories;

export const initialAttributes = priceList2026Attributes;

export const initialClients: ClientPartner[] = [
  { id: 'cl-1', name: 'BON! Cafe Français', logo: '/catalog/extracted_p2_img1.jpeg', category: 'cafe', sortOrder: 1 },
  { id: 'cl-2', name: 'Safia Cafe & Bakery', logo: '/catalog/extracted_p2_img2.jpeg', category: 'bakery', sortOrder: 2 },
  { id: 'cl-3', name: 'Apex Pizza', logo: '/catalog/extracted_p2_img3.jpeg', category: 'restaurant', sortOrder: 3 },
  { id: 'cl-4', name: 'Breadly', logo: '/catalog/extracted_p2_img4.jpeg', category: 'bakery', sortOrder: 4 },
  { id: 'cl-5', name: 'Чайкоф', logo: '/catalog/extracted_p2_img5.jpeg', category: 'cafe', sortOrder: 5 },
  { id: 'cl-6', name: 'Mövenpick Tashkent', logo: '/catalog/extracted_p2_img6.jpeg', category: 'hotel', sortOrder: 6 },
  { id: 'cl-7', name: 'Broccoli', logo: '/catalog/extracted_p2_img7.jpeg', category: 'restaurant', sortOrder: 7 },
  { id: 'cl-8', name: 'Gumma Xonim', logo: '/catalog/extracted_p2_img8.jpeg', category: 'cafe', sortOrder: 8 },
  { id: 'cl-9', name: 'DoubleTree by Hilton', logo: '/catalog/extracted_p2_img9.jpeg', category: 'hotel', sortOrder: 9 },
  { id: 'cl-10', name: 'Pie Republic', logo: '/catalog/extracted_p2_img10.jpeg', category: 'cafe', sortOrder: 10 },
  { id: 'cl-11', name: 'Sariq Bola Pizza', logo: '/catalog/extracted_p2_img11.jpeg', category: 'restaurant', sortOrder: 11 },
  { id: 'cl-12', name: 'Positano', logo: '/catalog/extracted_p2_img12.jpeg', category: 'restaurant', sortOrder: 12 },
  { id: 'cl-13', name: 'Tarelka Bistro', logo: '/catalog/extracted_p2_img13.jpeg', category: 'restaurant', sortOrder: 13 },
  { id: 'cl-14', name: 'Benedict Cafe', logo: '/catalog/extracted_p2_img14.jpeg', category: 'cafe', sortOrder: 14 },
  { id: 'cl-15', name: 'Shavi', logo: '/catalog/extracted_p2_img15.jpeg', category: 'restaurant', sortOrder: 15 },
  { id: 'cl-16', name: 'Unique', logo: '/catalog/extracted_p3_img1.jpeg', category: 'restaurant', sortOrder: 16 },
  { id: 'cl-17', name: 'Arboroma', logo: '/catalog/extracted_p3_img3.jpeg', category: 'restaurant', sortOrder: 17 },
  { id: 'cl-18', name: 'Zarqand', logo: '/catalog/extracted_p3_img5.jpeg', category: 'bakery', sortOrder: 18 },
  { id: 'cl-19', name: 'Big Chefs', logo: '/catalog/extracted_p3_img11.jpeg', category: 'restaurant', sortOrder: 19 },
  { id: 'cl-20', name: 'Minor Somsa', logo: '/catalog/extracted_p3_img15.jpeg', category: 'restaurant', sortOrder: 20 },
];

export const initialBanners: Banner[] = [
  {
    id: 'ban-bags',
    titleRu: 'Сверхпрочные мусорные мешки SANPACK',
    titleUz: 'SANPACK o‘ta mustahkam chiqindi qoplari',
    titleEn: 'SANPACK Heavy-Duty Trash Bags',
    titleZh: 'SANPACK 超强垃圾袋',
    subtitleRu: 'Собственное производство в Ташкенте. Все размеры от 40 до 240 литров с гарантией прочности.',
    subtitleUz: 'Toshkentda o‘z ishlab chiqarishimiz. 40 litrdan 240 litrgacha barcha o‘lchamlar mustahkamlik kafolati bilan.',
    subtitleEn: 'Direct manufacturer in Tashkent. All sizes from 40 to 240 liters with guaranteed tear resistance.',
    subtitleZh: '塔什干自有生产。40 至 240 升多种规格，坚固耐用。',
    imageDesktop: '/promo/banner-bags-desktop.png',
    imageMobile: '/promo/banner-bags-mobile.png',
    buttonTextRu: 'В каталог пакетов',
    buttonTextUz: 'Paketlar katalogi',
    buttonTextEn: 'View trash bags',
    buttonTextZh: '查看垃圾袋',
    link: '/catalog/musornye-pakety',
    sortOrder: 1,
    active: true,
  },
  {
    id: 'ban-meat',
    titleRu: 'Свежее мясо по лучшим ценам на рынке',
    titleUz: 'Bozordagi eng yaxshi narxlarda yangi go‘sht',
    titleEn: 'Fresh Meat at the Best Market Prices',
    titleZh: '优选新鲜肉类，市场好价',
    subtitleRu: 'Прямые оптовые поставки отборной говядины и мяса птицы для ресторанов и кафе.',
    subtitleUz: 'Restoran va kafelar uchun saralangan mol va tovuq go‘shtini to‘g‘ridan-to‘g‘ri ulgurji yetkazib berish.',
    subtitleEn: 'Direct wholesale supply of selected beef and poultry for restaurants, cafes, and HoReCa.',
    subtitleZh: '为餐厅、咖啡馆及 HoReCa 客户直供优选牛肉和禽肉。',
    imageDesktop: '/promo/banner-meat-desktop.png',
    imageMobile: '/promo/banner-meat-mobile.png',
    buttonTextRu: 'Смотреть продукцию',
    buttonTextUz: 'Mahsulotlarni ko‘rish',
    buttonTextEn: 'View products',
    buttonTextZh: '查看商品',
    link: '/catalog/produkty-pitaniya',
    sortOrder: 2,
    active: true,
  },
  {
    id: 'ban-greens',
    titleRu: 'Свежая зелень и микрозелень Novagreen',
    titleUz: 'Novagreen yangi ko‘katlar va mikrozavq',
    titleEn: 'Novagreen Fresh Greens & Microgreens',
    titleZh: 'Novagreen 新鲜香草与微型菜',
    subtitleRu: 'Ежедневный срез, ресторанная свежесть и отборный контроль качества для шеф-поваров.',
    subtitleUz: 'Har kuni yangi uzilgan, oshpazlar uchun restoran darajasidagi saralangan sifat.',
    subtitleEn: 'Daily harvest, chef-grade freshness and premium quality control.',
    subtitleZh: '每日鲜采，为专业厨师提供餐厅级新鲜度与精选品质。',
    imageDesktop: '/promo/banner-greens-desktop.png',
    imageMobile: '/promo/banner-greens-mobile.png',
    buttonTextRu: 'Выбрать зелень',
    buttonTextUz: 'Ko‘katlarni tanlash',
    buttonTextEn: 'Explore greens',
    buttonTextZh: '选购新鲜香草',
    link: '/catalog/svezhaya-zelen-novagreen',
    sortOrder: 3,
    active: true,
  },
];

export const initialProducts = priceList2026Products;
