import { Category, Product, Attribute, ClientPartner, Banner, SiteSettings } from '@/types';

export const initialSiteSettings: SiteSettings = {
  company: {
    name: 'SANPACK',
    logo: '/logo-sanpack.svg',
    favicon: '/favicon.ico',
    descriptionRu: 'Комплексный поставщик упаковки, расходных материалов и продуктов питания для HoReCa',
    descriptionUz: 'HoReCa uchun qadoqlash, sarf materiallari va oziq-ovqat mahsulotlarining kompleks yetkazib beruvchisi',
  },
  contacts: {
    phone1: '+998 99 851 05 06',
    phone2: '+998 99 232 39 99',
    email: 'info@sanpack.uz',
    addressRu: 'г. Ташкент, Сергелийский р-н, ул. Янги Сергели, 14А',
    addressUz: 'Toshkent sh., Sergeli t-ni, Yangi Sergeli ko‘ch., 14A',
    workingHoursRu: 'Пн — Сб: 09:00 - 18:00',
    workingHoursUz: 'Du — Sha: 09:00 - 18:00',
    telegram: 'https://t.me/sanpack_uz',
    whatsapp: 'https://wa.me/998998510506',
    cityRu: 'Ташкент',
    cityUz: 'Toshkent',
  },
  salesMode: 'request_only',
  commerce: {
    currency: 'UZS',
    checkoutFields: {
      name: true,
      phone: true,
    },
  },
  locale: {
    defaultLanguage: 'ru',
    supportedLanguages: ['ru'],
  },
  design: {
    designVersion: 2,
    primaryColor: '#0F6E43',
    secondaryColor: '#DCE9AF',
    borderRadius: 8,
    themeMode: 'light',
    fontPair: 'brand',
  },
  seo: {
    defaultTitleRu: 'SANPACK — Упаковка, расходные материалы и продукты для HoReCa в Ташкенте',
    defaultTitleUz: 'SANPACK — Toshkentda HoReCa uchun qadoqlash, sarf materiallari va oziq-ovqat',
    defaultDescriptionRu: 'Производство и оптовые поставки мусорных мешков, пакетов, перчаток, фольги, стрейч-пленки, бакалеи и полиграфии для ресторанов, отелей и бизнеса.',
    defaultDescriptionUz: 'Restoranlar, mehmonxonalar va biznes uchun chiqindi qoplari, paketlar, qo‘lqoplar, folga, strech plyonka va oziq-ovqat mahsulotlarini ulgurji yetkazib berish.',
  },
};

export const initialCategories: Category[] = [
  {
    id: 'cat-packaging',
    slug: 'packaging',
    titleRu: 'Упаковка и пакеты',
    titleUz: 'Qadoqlash va paketlar',
    descriptionRu: 'Полиэтиленовые пакеты, мусорные мешки, фасовочные рулонные пакеты и упаковка для пиццы.',
    descriptionUz: 'Polietilen paketlar, chiqindi qoplari, rulondagi paketlar va pitsa uchun qadoqlar.',
    image: '/catalog/page_4.webp',
    icon: 'Package',
    status: 'active',
    sortOrder: 1,
  },
  {
    id: 'cat-trash-bags',
    parentId: 'cat-packaging',
    slug: 'meshki-dlya-musora',
    titleRu: 'Мешки для мусора',
    titleUz: 'Chiqindi qoplari',
    descriptionRu: 'Прочные полиэтиленовые мешки для мусора SANPACK от 20 до 240 литров.',
    descriptionUz: '20 litrdan 240 litrgacha bo‘lgan SANPACK mustahkam chiqindi qoplari.',
    image: '/catalog/extracted_p4_img1.jpeg',
    icon: 'Trash2',
    status: 'active',
    sortOrder: 10,
  },
  {
    id: 'cat-tshirt-bags',
    parentId: 'cat-packaging',
    slug: 'pakety-mayka',
    titleRu: 'Пакеты «Майка» и рулонные',
    titleUz: '«Mayka» va rulonli paketlar',
    descriptionRu: 'Пакеты маечного типа высокой прочности (3–50 кг) и рулонные пакеты.',
    descriptionUz: 'Mustahkam mayka paketlar (3–50 kg) va rulonli paketlar.',
    image: '/catalog/commercial_packaging_10.webp',
    icon: 'ShoppingBag',
    status: 'active',
    sortOrder: 11,
  },
  {
    id: 'cat-consumables',
    slug: 'consumables',
    titleRu: 'Расходные материалы',
    titleUz: 'Sarf materiallari',
    descriptionRu: 'Перчатки, фольга, стрейч-пленка, пергамент и вакуумная пленка.',
    descriptionUz: 'Qo‘lqoplar, folga, strech-plyonka, pergament va vakuum plyonka.',
    image: '/catalog/page_5.png',
    icon: 'Shield',
    status: 'active',
    sortOrder: 2,
  },
  {
    id: 'cat-gloves',
    parentId: 'cat-consumables',
    slug: 'perchatki',
    titleRu: 'Перчатки',
    titleUz: 'Qo‘lqoplar',
    descriptionRu: 'Одноразовые полиэтиленовые, нитриловые и хозяйственные резиновые перчатки.',
    descriptionUz: 'Bir martalik polietilen, nitril va xo‘jalik rezin qo‘lqoplari.',
    image: '/catalog/extracted_p5_img7.jpeg',
    icon: 'Hand',
    status: 'active',
    sortOrder: 20,
  },
  {
    id: 'cat-film-foil',
    parentId: 'cat-consumables',
    slug: 'folga-i-plenka',
    titleRu: 'Фольга, плёнка и пергамент',
    titleUz: 'Folga, plyonka va pergament',
    descriptionRu: 'Алюминиевая пищевая фольга, стрейч-пленка, пергамент и вакуумная упаковка.',
    descriptionUz: 'Oziq-ovqat alyuminiy folgasi, strech-plyonka, pergament va vakuum qadoq.',
    image: '/catalog/extracted_p5_img1.jpeg',
    icon: 'Film',
    status: 'active',
    sortOrder: 21,
  },
  {
    id: 'cat-food',
    slug: 'food-horeca',
    titleRu: 'Продукты питания',
    titleUz: 'Oziq-ovqat mahsulotlari',
    descriptionRu: 'Бакалея, рис, мука, сливочное масло, сыры, мясо и свежая зелень Novagreen.',
    descriptionUz: 'Baqolchilik, guruch, un, sariyog‘, pishloqlar, go‘sht va yangi ko‘katlar.',
    image: '/catalog/page_7.webp',
    icon: 'Utensils',
    status: 'active',
    sortOrder: 3,
  },
  {
    id: 'cat-groceries',
    parentId: 'cat-food',
    slug: 'bakaleya',
    titleRu: 'Бакалея, рис и мука',
    titleUz: 'Baqolchilik, guruch va un',
    descriptionRu: 'Отборный рис Лазер и Аланга, гречка, нут, чечевица, мука, сахар и масло.',
    descriptionUz: 'Lazer va Alanga guruchi, grechka, noxat, yasmiq, un, shakar va yog‘.',
    image: '/catalog/extracted_p7_img1.jpeg',
    icon: 'Wheat',
    status: 'active',
    sortOrder: 30,
  },
  {
    id: 'cat-cheeses',
    parentId: 'cat-food',
    slug: 'syry-i-maslo',
    titleRu: 'Сыры и сливочное масло',
    titleUz: 'Pishloqlar va sariyog‘',
    descriptionRu: 'Сваля, Viola, Valio, Fitaki, Camembert, Brie, Parnidzio, Dorblu, Landana.',
    descriptionUz: 'Svalya, Viola, Valio, Fitaki, Camembert, Brie, Parnidzio, Dorblu, Landana.',
    image: '/catalog/extracted_p9_img1.jpeg',
    icon: 'PieChart',
    status: 'active',
    sortOrder: 31,
  },
  {
    id: 'cat-greens',
    parentId: 'cat-food',
    slug: 'svezhaya-zelen',
    titleRu: 'Свежая зелень Novagreen',
    titleUz: 'Yangi ko‘katlar Novagreen',
    descriptionRu: 'Свежая зелень, микрозелень, айсберг, руккола и листовые салаты напрямую с теплиц.',
    descriptionUz: 'Issiqxonalardan to‘g‘ridan-to‘g mevalar va yangi ko‘katlar.',
    image: '/catalog/extracted_p11_img1.jpeg',
    icon: 'Leaf',
    status: 'active',
    sortOrder: 32,
  },
  {
    id: 'cat-branding',
    slug: 'branding-polygraphy',
    titleRu: 'Полиграфия и брендирование',
    titleUz: 'Poligrafiya va brendlash',
    descriptionRu: 'Совместно с Nova Print: пакеты с логотипом, этикетки, меню, корпоративный мерч.',
    descriptionUz: 'Nova Print bilan birgalikda: logotipli paketlar, etiketkalar, menyu va merch.',
    image: '/catalog/extracted_p14_img1.jpeg',
    icon: 'Printer',
    status: 'active',
    sortOrder: 4,
  },
];

export const initialAttributes: Attribute[] = [
  {
    id: 'attr-material',
    key: 'material',
    titleRu: 'Материал',
    titleUz: 'Material',
    type: 'select',
    options: [
      { value: 'ПНД', labelRu: 'ПНД (HDPE)', labelUz: 'PND (HDPE)' },
      { value: 'ПВД', labelRu: 'ПВД (LDPE)', labelUz: 'PVD (LDPE)' },
      { value: 'Нитрил', labelRu: 'Нитрил', labelUz: 'Nitril' },
      { value: 'Резина', labelRu: 'Резина', labelUz: 'Rezina' },
      { value: 'Алюминий', labelRu: 'Алюминий', labelUz: 'Alyuminiy' },
      { value: 'ПВХ / Стрейч', labelRu: 'ПВХ / Стрейч', labelUz: 'PVX / Strech' },
      { value: 'Пергамент', labelRu: 'Пищевой пергамент', labelUz: 'Oziq-ovqat pergamenti' },
      { value: 'Полиэтилен', labelRu: 'Полиэтилен', labelUz: 'Polietilen' },
    ],
    filterable: true,
    required: false,
    cardVisible: true,
    productVisible: true,
    sortOrder: 1,
  },
  {
    id: 'attr-volume',
    key: 'volume',
    titleRu: 'Объём',
    titleUz: 'Hajmi',
    type: 'select',
    unit: 'л',
    categoryIds: ['cat-trash-bags', 'cat-packaging'],
    options: [
      { value: '20 л', labelRu: '20 литров', labelUz: '20 litr' },
      { value: '22 л', labelRu: '22 литра', labelUz: '22 litr' },
      { value: '41 л', labelRu: '41 литр', labelUz: '41 litr' },
      { value: '85 л', labelRu: '85 литров', labelUz: '85 litr' },
      { value: '160 л', labelRu: '160 литров', labelUz: '160 litr' },
      { value: '220 л', labelRu: '220 литров', labelUz: '220 litr' },
      { value: '240 л', labelRu: '240 литров', labelUz: '240 litr' },
    ],
    filterable: true,
    required: false,
    cardVisible: true,
    productVisible: true,
    sortOrder: 2,
  },
  {
    id: 'attr-thickness',
    key: 'thickness',
    titleRu: 'Толщина / Плотность',
    titleUz: 'Qalinligi / Zichligi',
    type: 'select',
    unit: 'мкм',
    options: [
      { value: '8 мкм', labelRu: '8 мкм', labelUz: '8 mkm' },
      { value: '10 мкм', labelRu: '10 мкм', labelUz: '10 mkm' },
      { value: '11 мкм', labelRu: '11 мкм', labelUz: '11 mkm' },
      { value: '12 мкм', labelRu: '12 мкм', labelUz: '12 mkm' },
      { value: '14 мкм', labelRu: '14 мкм', labelUz: '14 mkm' },
      { value: '15 мкм', labelRu: '15 мкм', labelUz: '15 mkm' },
      { value: '20 мкм', labelRu: '20 мкм', labelUz: '20 mkm' },
      { value: '25 мкм', labelRu: '25 мкм', labelUz: '25 mkm' },
      { value: '30 мкм', labelRu: '30 мкм', labelUz: '30 mkm' },
      { value: '40 мкм', labelRu: '40 мкм', labelUz: '40 mkm' },
    ],
    filterable: true,
    required: false,
    cardVisible: true,
    productVisible: true,
    sortOrder: 3,
  },
  {
    id: 'attr-weight',
    key: 'weight',
    titleRu: 'Фасовка / Вес',
    titleUz: 'Qadoq / Og‘irligi',
    type: 'select',
    categoryIds: ['cat-food', 'cat-groceries', 'cat-cheeses', 'cat-greens'],
    options: [
      { value: '20 гр', labelRu: '20 гр', labelUz: '20 gr' },
      { value: '60 гр', labelRu: '60 гр', labelUz: '60 gr' },
      { value: '150 гр', labelRu: '150 гр', labelUz: '150 gr' },
      { value: '250 гр', labelRu: '250 гр', labelUz: '250 gr' },
      { value: '400 гр', labelRu: '400 гр', labelUz: '400 gr' },
      { value: '500 гр', labelRu: '500 гр', labelUz: '500 gr' },
      { value: '1 кг', labelRu: '1 кг', labelUz: '1 kg' },
      { value: '2.5 кг', labelRu: '2.5 кг', labelUz: '2.5 kg' },
      { value: '3 кг', labelRu: '3 кг', labelUz: '3 kg' },
      { value: '5 кг', labelRu: '5 кг', labelUz: '5 kg' },
      { value: '50 кг', labelRu: '50 кг', labelUz: '50 kg' },
    ],
    filterable: true,
    required: false,
    cardVisible: true,
    productVisible: true,
    sortOrder: 4,
  },
  {
    id: 'attr-packaging-type',
    key: 'packaging_type',
    titleRu: 'Вид упаковки',
    titleUz: 'Qadoq turi',
    type: 'select',
    options: [
      { value: 'Рулон', labelRu: 'Рулон', labelUz: 'Rulon' },
      { value: 'Вакуумная упаковка', labelRu: 'Вакуумная упаковка', labelUz: 'Vakuum qadoq' },
      { value: 'Пачка', labelRu: 'Пачка', labelUz: 'Pachka' },
      { value: 'Брус', labelRu: 'Брус', labelUz: 'Brus' },
      { value: 'Контейнер / Лоток', labelRu: 'Контейнер / Лоток', labelUz: 'Konteyner' },
      { value: 'Мешок 50 кг', labelRu: 'Мешок 50 кг', labelUz: 'Qop 50 kg' },
      { value: 'Бутылка 1 л', labelRu: 'Бутылка 1 л', labelUz: 'Butilka 1 l' },
    ],
    filterable: true,
    required: false,
    cardVisible: true,
    productVisible: true,
    sortOrder: 5,
  },
  {
    id: 'attr-horeca-category',
    key: 'horeca_category',
    titleRu: 'Сегмент HoReCa',
    titleUz: 'HoReCa segmenti',
    type: 'select',
    options: [
      { value: 'Мусорные мешки', labelRu: 'Мусорные мешки', labelUz: 'Chiqindi qoplari' },
      { value: 'Пакеты Майка', labelRu: 'Пакеты Майка', labelUz: 'Mayka paketlar' },
      { value: 'Перчатки и Защита', labelRu: 'Перчатки и Защита', labelUz: 'Qo‘lqoplar' },
      { value: 'Плёнка и Фольга', labelRu: 'Плёнка и Фольга', labelUz: 'Plyonka va Folga' },
      { value: 'Свежая зелень Novagreen', labelRu: 'Свежая зелень Novagreen', labelUz: 'Yangi ko‘katlar' },
      { value: 'Сыры и Масло', labelRu: 'Сыры и Масло', labelUz: 'Pishloqlar va Sariyog‘' },
      { value: 'Бакалея и Мука', labelRu: 'Бакалея и Мука', labelUz: 'Baqolchilik va Un' },
      { value: 'Брендирование Nova Print', labelRu: 'Брендирование Nova Print', labelUz: 'Brendlash Nova Print' },
    ],
    filterable: true,
    required: false,
    cardVisible: true,
    productVisible: true,
    sortOrder: 6,
  },
];

export const initialClients: ClientPartner[] = [
  { id: 'cl-1', name: 'BON! Cafe Français', logo: '/catalog/extracted_p2_img1.jpeg', category: 'cafe', sortOrder: 1 },
  { id: 'cl-2', name: 'Safia Cafe & Bakery', logo: '/catalog/extracted_p2_img2.jpeg', category: 'bakery', sortOrder: 2 },
  { id: 'cl-3', name: 'Apex Pizza', logo: '/catalog/extracted_p2_img3.jpeg', category: 'restaurant', sortOrder: 3 },
  { id: 'cl-4', name: 'Breadly', logo: '/catalog/extracted_p2_img4.jpeg', category: 'bakery', sortOrder: 4 },
  { id: 'cl-5', name: 'Чайкоф', logo: '/catalog/extracted_p2_img5.jpeg', category: 'cafe', sortOrder: 5 },
  { id: 'cl-6', name: 'Mövenpick Tashkent', logo: '/catalog/extracted_p2_img6.jpeg', category: 'hotel', sortOrder: 6 },
  { id: 'cl-7', name: 'Broccoli', logo: '/catalog/extracted_p2_img7.jpeg', category: 'restaurant', sortOrder: 7 },
  { id: 'cl-8', name: 'Gumma Xonim', logo: '/catalog/extracted_p2_img8.jpeg', category: 'cafe', sortOrder: 8 },
  { id: 'cl-9', name: 'DoubleTree by Hilton', logo: '/catalog/extracted_p2_img9.jpeg', category: 'hotel', sortOrder: 9 },
  { id: 'cl-10', name: 'Pie Republic', logo: '/catalog/extracted_p2_img10.jpeg', category: 'cafe', sortOrder: 10 },
  { id: 'cl-11', name: 'Sariq Bola Pizza', logo: '/catalog/extracted_p2_img11.jpeg', category: 'restaurant', sortOrder: 11 },
  { id: 'cl-12', name: 'Positano', logo: '/catalog/extracted_p2_img12.jpeg', category: 'restaurant', sortOrder: 12 },
  { id: 'cl-13', name: 'Tarelka Bistro', logo: '/catalog/extracted_p2_img13.jpeg', category: 'restaurant', sortOrder: 13 },
  { id: 'cl-14', name: 'Benedict Cafe', logo: '/catalog/extracted_p2_img14.jpeg', category: 'cafe', sortOrder: 14 },
  { id: 'cl-15', name: 'Shavi', logo: '/catalog/extracted_p2_img15.jpeg', category: 'restaurant', sortOrder: 15 },
  { id: 'cl-16', name: 'Unique', logo: '/catalog/extracted_p3_img1.jpeg', category: 'restaurant', sortOrder: 16 },
  { id: 'cl-17', name: 'Arboroma', logo: '/catalog/extracted_p3_img3.jpeg', category: 'restaurant', sortOrder: 17 },
  { id: 'cl-18', name: 'Zarqand', logo: '/catalog/extracted_p3_img5.jpeg', category: 'bakery', sortOrder: 18 },
  { id: 'cl-19', name: 'Big Chefs', logo: '/catalog/extracted_p3_img11.jpeg', category: 'restaurant', sortOrder: 19 },
  { id: 'cl-20', name: 'Minor Somsa', logo: '/catalog/extracted_p3_img15.jpeg', category: 'restaurant', sortOrder: 20 },
];

export const initialBanners: Banner[] = [
  {
    id: 'ban-1',
    titleRu: 'Собственное производство мусорных мешков и пакетов',
    titleUz: 'Chiqindi qoplari va paketlar o‘z ishlab chiqarishimiz',
    subtitleRu: 'Прямые оптовые поставки по Ташкенту и Узбекистану от производителя SANPACK',
    subtitleUz: 'SANPACK ishlab chiqaruvchisidan Toshkent va O‘zbekiston bo‘ylab ulgurji yetkazib berish',
    imageDesktop: '/promo/sanpack-supply-desktop.webp',
    imageMobile: '/promo/sanpack-supply-mobile.webp',
    buttonTextRu: 'Перейти в каталог',
    buttonTextUz: 'Katalogni ko‘rish',
    link: '/catalog',
    sortOrder: 1,
    active: true,
  },
];

export const initialProducts: Product[] = [
  {
  "id": "prod-tb-20l",
  "slug": "meshki-dlya-musora-sanpack-20l",
  "sku": "SP-TB-4550-20L",
  "status": "published",
  "categoryId": "cat-trash-bags",
  "categorySlug": "meshki-dlya-musora",
  "titleRu": "Мешки для мусора SANPACK 45 × 50 см, 20 литров (40 шт)",
  "titleUz": "SANPACK chiqindi qoplari 45 × 50 sm, 20 litr (40 dona)",
  "shortDescriptionRu": "Прочные мусорные мешки в рулонах по 40 штук для офисов и номеров отелей.",
  "shortDescriptionUz": "Ofislar va mehmonxonalar uchun 40 donalik rulondagi chiqindi qoplari.",
  "descriptionRu": "Высококачественные полиэтиленовые мешки для мусора объемом 20 литров от производителя SANPACK. Перфорация для легкого отрыва, герметичный донный шов.",
  "descriptionUz": "SANPACK ishlab chiqaruvchisidan 20 litr hajmli yuqori sifatli polietilen chiqindi qoplari. Oson uzish uchun teshiklar, mustahkam pastki chok.",
  "images": [
    "/catalog/sanpack_trash_bag_roll_1_nobg.png"
  ],
  "mainImage": "/catalog/sanpack_trash_bag_roll_1_nobg.png",
  "attributes": {
      "material": "ПНД",
      "thickness": "15 мкм",
      "volume": "20 л",
      "packaging_type": "Рулон",
      "horeca_category": "Мусорные мешки"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 10,
  "salesUnit": "рулон",
  "featured": true,
  "newProduct": false,
  "ownProduction": true,
  "sortOrder": 1,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-tb-22l",
  "slug": "meshki-dlya-musora-sanpack-22l",
  "sku": "SP-TB-4560-22L",
  "status": "published",
  "categoryId": "cat-trash-bags",
  "categorySlug": "meshki-dlya-musora",
  "titleRu": "Мешки для мусора SANPACK 45 × 60 см, 22 литра (30 шт)",
  "titleUz": "SANPACK chiqindi qoplari 45 × 60 sm, 22 litr (30 dona)",
  "shortDescriptionRu": "Удлиненные мешки в рулонах по 30 штук для стандартных урн.",
  "shortDescriptionUz": "Standart savatlar uchun 30 donalik rulondagi qoplar.",
  "descriptionRu": "Полиэтиленовые мешки для мусора 22 литра. Оптимальны для заведений общепита, санузлов кафе и бытового использования.",
  "descriptionUz": "22 litrli polietilen chiqindi qoplari. Umumiy ovqatlanish va maishiy foydalanish uchun qulay.",
  "images": [
    "/catalog/sanpack_trash_bag_roll_2_nobg.png"
  ],
  "mainImage": "/catalog/sanpack_trash_bag_roll_2_nobg.png",
  "attributes": {
      "material": "ПНД",
      "thickness": "15 мкм",
      "volume": "22 л",
      "packaging_type": "Рулон",
      "horeca_category": "Мусорные мешки"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 10,
  "salesUnit": "рулон",
  "featured": false,
  "newProduct": false,
  "ownProduction": true,
  "sortOrder": 2,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-tb-41l",
  "slug": "meshki-dlya-musora-sanpack-41l",
  "sku": "SP-TB-5070-41L",
  "status": "published",
  "categoryId": "cat-trash-bags",
  "categorySlug": "meshki-dlya-musora",
  "titleRu": "Мешки для мусора SANPACK 50 × 70 см, 41 литр (25 шт)",
  "titleUz": "SANPACK chiqindi qoplari 50 × 70 sm, 41 litr (25 dona)",
  "shortDescriptionRu": "Средний объем 41 литр в рулонах по 25 штук для ресторанных кухонь.",
  "shortDescriptionUz": "Restoran oshxonalari uchun 25 donalik rulondagi 41 litrli qoplar.",
  "descriptionRu": "Мешки SANPACK 41 литр разработаны для средних баков и кухонных урн HoReCa.",
  "descriptionUz": "SANPACK 41 litrli qoplar HoReCa oshxona savatlari uchun mo‘ljallangan.",
  "images": [
    "/catalog/sanpack_trash_bag_roll_3_nobg.png"
  ],
  "mainImage": "/catalog/sanpack_trash_bag_roll_3_nobg.png",
  "attributes": {
      "material": "ПНД",
      "thickness": "20 мкм",
      "volume": "41 л",
      "packaging_type": "Рулон",
      "horeca_category": "Мусорные мешки"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 10,
  "salesUnit": "рулон",
  "featured": true,
  "newProduct": false,
  "ownProduction": true,
  "sortOrder": 3,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-tb-85l",
  "slug": "meshki-dlya-musora-sanpack-85l",
  "sku": "SP-TB-6090-85L",
  "status": "published",
  "categoryId": "cat-trash-bags",
  "categorySlug": "meshki-dlya-musora",
  "titleRu": "Мешки для мусора SANPACK 60 × 90 см, 85 литров (9 шт)",
  "titleUz": "SANPACK chiqindi qoplari 60 × 90 sm, 85 litr (9 dona)",
  "shortDescriptionRu": "Большие усиленные мешки для производственных кухонь и фудкортов.",
  "shortDescriptionUz": "Oshxonalar va fudkortlar uchun yirik mustahkamlangan qoplar.",
  "descriptionRu": "Профессиональные мешки объемом 85 литров для тяжелых и влажных отходов пищеблоков.",
  "descriptionUz": "Oziq-ovqat bloki og‘ir chiqindilari uchun 85 litrli professional qoplar.",
  "images": [
    "/catalog/sanpack_trash_bag_roll_4_nobg.png"
  ],
  "mainImage": "/catalog/sanpack_trash_bag_roll_4_nobg.png",
  "attributes": {
      "material": "ПНД",
      "thickness": "20 мкм",
      "volume": "85 л",
      "packaging_type": "Рулон",
      "horeca_category": "Мусорные мешки"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 20,
  "salesUnit": "рулон",
  "featured": true,
  "newProduct": true,
  "ownProduction": true,
  "sortOrder": 4,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-tb-160l",
  "slug": "meshki-dlya-musora-sanpack-160l",
  "sku": "SP-TB-80110-160L",
  "status": "published",
  "categoryId": "cat-trash-bags",
  "categorySlug": "meshki-dlya-musora",
  "titleRu": "Мешки для мусора SANPACK 80 × 110 см, 160 литров (7 шт)",
  "titleUz": "SANPACK chiqindi qoplari 80 × 110 sm, 160 litr (7 dona)",
  "shortDescriptionRu": "Сверхпрочные мешки для больших баков и тележек клининга.",
  "shortDescriptionUz": "Yirik baklar va klining aravachalari uchun o‘ta mustahkam qoplar.",
  "descriptionRu": "Мешки SANPACK 160 литров. Высокая плотность полиэтилена, надежное удержание разрывов.",
  "descriptionUz": "SANPACK 160 litrli qoplar. Polietilening yuqori zichligi, yirtilishga chidamlilik.",
  "images": [
    "/catalog/sanpack_trash_bag_roll_5_nobg.png"
  ],
  "mainImage": "/catalog/sanpack_trash_bag_roll_5_nobg.png",
  "attributes": {
      "material": "ПНД",
      "thickness": "30 мкм",
      "volume": "160 л",
      "packaging_type": "Рулон",
      "horeca_category": "Мусорные мешки"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 15,
  "salesUnit": "рулон",
  "featured": false,
  "newProduct": false,
  "ownProduction": true,
  "sortOrder": 5,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-tb-220l",
  "slug": "meshki-dlya-musora-sanpack-220l",
  "sku": "SP-TB-90110-220L",
  "status": "published",
  "categoryId": "cat-trash-bags",
  "categorySlug": "meshki-dlya-musora",
  "titleRu": "Мешки для мусора SANPACK 90 × 110 см, 220 литров (7 шт в упаковке)",
  "titleUz": "SANPACK chiqindi qoplari 90 × 110 sm, 220 litr (7 dona o‘ramda)",
  "shortDescriptionRu": "Огромный объем 220 литров для уличных и складских контейнеров.",
  "shortDescriptionUz": "Konteynerlar uchun 220 litrli ultrakatta qoplar.",
  "descriptionRu": "Особо прочные мешки 220 литров в плотной упаковке для складов, гипермаркетов и выездных сервисов.",
  "descriptionUz": "Omborlar va gipermarketlar uchun 220 litrli o‘ta mustahkam qoplar.",
  "images": [
    "/catalog/sanpack_trash_bag_roll_6_nobg.png"
  ],
  "mainImage": "/catalog/sanpack_trash_bag_roll_6_nobg.png",
  "attributes": {
      "material": "ПНД",
      "thickness": "15 мкм",
      "volume": "20 л",
      "packaging_type": "Рулон",
      "horeca_category": "Мусорные мешки"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 10,
  "salesUnit": "упаковка",
  "featured": false,
  "newProduct": false,
  "ownProduction": true,
  "sortOrder": 6,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-tb-240l-6",
  "slug": "meshki-dlya-musora-sanpack-240l-6pcs",
  "sku": "SP-TB-90120-240L-6",
  "status": "published",
  "categoryId": "cat-trash-bags",
  "categorySlug": "meshki-dlya-musora",
  "titleRu": "Мешки для мусора SANPACK 90 × 120 см, 240 литров (6 шт)",
  "titleUz": "SANPACK chiqindi qoplari 90 × 120 sm, 240 litr (6 dona)",
  "shortDescriptionRu": "Гигантские мешки 240 литров под пластиковые баки на колесах.",
  "shortDescriptionUz": "Gildirakli baklar uchun 240 litrli gigant qoplar.",
  "descriptionRu": "Профессиональные мешки 240 литров SANPACK (6 шт в рулоне) под стандартные мусорные евроконтейнеры.",
  "descriptionUz": "Standart yevrokonteynerlar uchun SANPACK 240 litrli (6 dona) professional qoplar.",
  "images": [
    "/catalog/sanpack_trash_bag_roll_10.png"
  ],
  "mainImage": "/catalog/sanpack_trash_bag_roll_10.png",
  "attributes": {
      "material": "ПНД",
      "thickness": "30 мкм",
      "volume": "240 л",
      "packaging_type": "Рулон",
      "horeca_category": "Мусорные мешки"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 10,
  "salesUnit": "рулон",
  "featured": true,
  "newProduct": true,
  "ownProduction": true,
  "sortOrder": 7,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-tb-240l-11",
  "slug": "meshki-dlya-musora-sanpack-240l-11pcs",
  "sku": "SP-TB-90120-240L-11",
  "status": "published",
  "categoryId": "cat-trash-bags",
  "categorySlug": "meshki-dlya-musora",
  "titleRu": "Мешки для мусора SANPACK 90 × 120 см, 240 литров (11 шт)",
  "titleUz": "SANPACK chiqindi qoplari 90 × 120 sm, 240 litr (11 dona)",
  "shortDescriptionRu": "Экономичный рулон 11 штук повышенного объема 240 литров.",
  "shortDescriptionUz": "240 litrli 11 donalik tejamkor rulon.",
  "descriptionRu": "Максимальная фасовка 11 штук в рулоне для клининга и крупных пищевых производств.",
  "descriptionUz": "Klining va yirik ishlab chiqarishlar uchun 11 donalik maksimal faovka.",
  "images": [
    "/catalog/commercial_packaging_11_nobg.png"
  ],
  "mainImage": "/catalog/commercial_packaging_11_nobg.png",
  "attributes": {
      "material": "ПНД",
      "thickness": "30 мкм",
      "volume": "240 л",
      "packaging_type": "Рулон",
      "horeca_category": "Мусорные мешки"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 10,
  "salesUnit": "рулон",
  "featured": false,
  "newProduct": true,
  "ownProduction": true,
  "sortOrder": 8,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-foil-alu",
  "slug": "alyuminievaya-folga-pishchevaya",
  "sku": "SP-ALU-FOIL",
  "status": "published",
  "categoryId": "cat-film-foil",
  "categorySlug": "folga-i-plenka",
  "titleRu": "Алюминиевая пищевая фольга SANPACK",
  "titleUz": "SANPACK oziq-ovqat alyuminiy folgasi",
  "shortDescriptionRu": "Жаропрочная плотная фольга для запекания, гриля и упаковки горячих блюд.",
  "shortDescriptionUz": "Issiqqa chidamli folga pishirish va issiq taomlarni qadoqlash uchun.",
  "descriptionRu": "Пищевая алюминиевая фольга для профессиональной кухни HoReCa. Удерживает сочность блюд и сохраняет температуру.",
  "descriptionUz": "HoReCa professional oshxonasi uchun oziq-ovqat alyuminiy folgasi. Sersuvlik va haroratni saqlaydi.",
  "images": [
    "/catalog/extracted_p5_img6.jpeg"
  ],
  "mainImage": "/catalog/extracted_p5_img6.jpeg",
  "attributes": {
      "material": "Алюминий",
      "thickness": "11 мкм",
      "packaging_type": "Рулон",
      "horeca_category": "Плёнка и Фольга"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 5,
  "salesUnit": "рулон",
  "featured": true,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 10,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-stretch-film",
  "slug": "pishchevaya-streych-plenka",
  "sku": "SP-STR-FILM",
  "status": "published",
  "categoryId": "cat-film-foil",
  "categorySlug": "folga-i-plenka",
  "titleRu": "Пищевая стрейч-плёнка SANPACK",
  "titleUz": "SANPACK oziq-ovqat strech plyonkasi",
  "shortDescriptionRu": "Эластичная прозрачная плёнка для герметичной упаковки продуктов.",
  "shortDescriptionUz": "Mahsulotlarni zich qadoqlash uchun elastik shaffof plyonka.",
  "descriptionRu": "Пищевая стрейч-пленка повышенной растяжимости и липкости. Предотвращает заветривание и впитывание посторонних запахов.",
  "descriptionUz": "Yuqori cho'ziluvchan va yopishqoq oziq-ovqat strech plyonkasi.",
  "images": [
    "/catalog/extracted_p5_img7.jpeg"
  ],
  "mainImage": "/catalog/extracted_p5_img7.jpeg",
  "attributes": {
      "material": "ПВХ / Стрейч",
      "thickness": "8 мкм",
      "packaging_type": "Рулон",
      "horeca_category": "Плёнка и Фольга"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 5,
  "salesUnit": "рулон",
  "featured": true,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 11,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-parchment-paper",
  "slug": "pergamentnaya-bumaga-dlya-vypechki",
  "sku": "SP-PARCH-PAPER",
  "status": "published",
  "categoryId": "cat-film-foil",
  "categorySlug": "folga-i-plenka",
  "titleRu": "Пергаментная бумага для выпечки SANPACK",
  "titleUz": "SANPACK pishirish uchun pergament qog‘ozi",
  "shortDescriptionRu": "Пищевой силиконизированный пергамент для пекарен и кондитерских.",
  "shortDescriptionUz": "Novvoyxonalar uchun oziq-ovqat pergament qog'ozi.",
  "descriptionRu": "Пергаментная бумага с антипригарными свойствами. Выдерживает температуру до 230°C.",
  "descriptionUz": "Yopishishga qarshi xususiyatga ega pergament qog'ozi. 230°C gacha haroratga chidamli.",
  "images": [
    "/catalog/extracted_p5_img8.jpeg"
  ],
  "mainImage": "/catalog/extracted_p5_img8.jpeg",
  "attributes": {
      "material": "Пергамент",
      "thickness": "40 мкм",
      "packaging_type": "Рулон",
      "horeca_category": "Плёнка и Фольга"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 5,
  "salesUnit": "рулон",
  "featured": false,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 12,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-vacuum-film",
  "slug": "plenka-dlya-vakuumnoy-upakovki",
  "sku": "SP-VAC-FILM",
  "status": "published",
  "categoryId": "cat-film-foil",
  "categorySlug": "folga-i-plenka",
  "titleRu": "Плёнка для вакуумной упаковки SANPACK",
  "titleUz": "SANPACK vakuumli qadoqlash uchun plyonka",
  "shortDescriptionRu": "Барьерная плёнка для вакууматоров, заморозки и технологии sous-vide.",
  "shortDescriptionUz": "Muzlatish va sous-vide texnologiyasi uchun vakuum plyonkasi.",
  "descriptionRu": "Высокобарьерная вакуумная пленка для долгосрочного хранения мяса, сыров и готовых полуфабрикатов.",
  "descriptionUz": "Go'sht, pishloq va yarim tayyor mahsulotlarni uzoq muddat saqlash uchun vakuum plyonkasi.",
  "images": [
    "/catalog/extracted_p5_img9.jpeg"
  ],
  "mainImage": "/catalog/extracted_p5_img9.jpeg",
  "attributes": {
      "material": "Полиэтилен",
      "thickness": "20 мкм",
      "packaging_type": "Вакуумная упаковка",
      "horeca_category": "Плёнка и Фольга"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 5,
  "salesUnit": "рулон",
  "featured": false,
  "newProduct": true,
  "ownProduction": false,
  "sortOrder": 13,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-poly-gloves",
  "slug": "odnorazovye-polietilenovye-perchatki",
  "sku": "SP-GLV-PE",
  "status": "published",
  "categoryId": "cat-gloves",
  "categorySlug": "perchatki",
  "titleRu": "Одноразовые полиэтиленовые перчатки SANPACK (100 шт)",
  "titleUz": "Bir martalik polietilen qo‘lqoplar SANPACK (100 dona)",
  "shortDescriptionRu": "Легкие прозрачные перчатки для фасовки и контакта с пищевыми продуктами.",
  "shortDescriptionUz": "Mahsulotlarni qadoqlash uchun yengil shaffof qo'lqoplar.",
  "descriptionRu": "Гигиеничные одноразовые перчатки из ПНД в яркой фирменной коробке SANPACK. Необходимы для поваров, кондитеров и продавцов.",
  "descriptionUz": "SANPACK yorqin qutisidagi PND bir martalik gigiyenik qo'lqoplar.",
  "images": [
    "/catalog/extracted_p5_img3.jpeg"
  ],
  "mainImage": "/catalog/extracted_p5_img3.jpeg",
  "attributes": {
      "material": "Полиэтилен",
      "packaging_type": "Пачка",
      "horeca_category": "Перчатки и Защита"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 20,
  "salesUnit": "упаковка",
  "featured": true,
  "newProduct": false,
  "ownProduction": true,
  "sortOrder": 14,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-nitrile-gloves",
  "slug": "odnorazovye-nitrilovye-perchatki-touchflex",
  "sku": "SP-GLV-NITRIL",
  "status": "published",
  "categoryId": "cat-gloves",
  "categorySlug": "perchatki",
  "titleRu": "Одноразовые нитриловые перчатки TouchFlex (100 шт)",
  "titleUz": "Bir martalik nitril qo‘lqoplar TouchFlex (100 dona)",
  "shortDescriptionRu": "Прочные неопудренные нитриловые перчатки черные/синие.",
  "shortDescriptionUz": "Mustahkam nitril kukunlanmagan qo'lqoplar.",
  "descriptionRu": "Нитриловые перчатки TouchFlex повышенной эластичности. Отличный чувствительный захват, защита от жиров, масел и химикатов.",
  "descriptionUz": "Yuqori elastiklikka ega TouchFlex nitril qo'lqoplari. Yog'lar va kimyoviy moddalardan hidsiz va xavfsiz himoya.",
  "images": [
    "/catalog/extracted_p5_img1.jpeg"
  ],
  "mainImage": "/catalog/extracted_p5_img1.jpeg",
  "attributes": {
      "material": "Нитрил",
      "packaging_type": "Пачка",
      "horeca_category": "Перчатки и Защита"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 10,
  "salesUnit": "упаковка",
  "featured": true,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 15,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-rubber-gloves",
  "slug": "khozyaystvennye-rezinovye-perchatki",
  "sku": "SP-GLV-RUBBER",
  "status": "published",
  "categoryId": "cat-gloves",
  "categorySlug": "perchatki",
  "titleRu": "Хозяйственные резиновые перчатки желтые",
  "titleUz": "Xo‘jalik uchun rezina qo‘lqoplar sariq",
  "shortDescriptionRu": "Плотные резиновые перчатки для уборки, мойки посуды и клининга.",
  "shortDescriptionUz": "Idish yuvish va klining uchun qalin rezina qo'lqoplar.",
  "descriptionRu": "Многоразовые латексные перчатки с рельефной поверхностью на пальцах для уборки помещений и работы с бытовой химией.",
  "descriptionUz": "Xonalarni tozalash va maishiy kimyo билан ishlash uchun ko'p martalik lateks qo'lqoplar.",
  "images": [
    "/catalog/extracted_p5_img2.jpeg"
  ],
  "mainImage": "/catalog/extracted_p5_img2.jpeg",
  "attributes": {
      "material": "Резина",
      "packaging_type": "Пачка",
      "horeca_category": "Перчатки и Защита"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 20,
  "salesUnit": "пара",
  "featured": false,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 16,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-tshirt-3kg",
  "slug": "pakety-mayka-sanpack-3kg",
  "sku": "SP-MS-3KG-100",
  "status": "published",
  "categoryId": "cat-tshirt-bags",
  "categorySlug": "pakety-mayka",
  "titleRu": "Пакеты «Майка» SANPACK ULTRA 3 кг (29 × 41 см, 100 шт)",
  "titleUz": "SANPACK ULTRA «Mayka» paketlari 3 kg (29 × 41 sm, 100 dona)",
  "shortDescriptionRu": "Пакеты маечного типа до 3 кг для аптек, супермаркетов и небольших покупок.",
  "shortDescriptionUz": "Kichik xaridlar uchun 3 kg gacha mayka paketlar.",
  "descriptionRu": "Пакеты «Майка» SANPACK ULTRA грузоподъемностью до 3 кг. Плотный штампованный полиэтилен, удобные ручки.",
  "descriptionUz": "SANPACK ULTRA 3 kg gacha yuk ko'taruvchi mayka paketlari.",
  "images": [
    "/catalog/commercial_packaging_10.webp"
  ],
  "mainImage": "/catalog/commercial_packaging_10.webp",
  "attributes": {
      "material": "ПНД",
      "thickness": "10 мкм",
      "horeca_category": "Пакеты Майка"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 50,
  "salesUnit": "упаковка",
  "featured": true,
  "newProduct": false,
  "ownProduction": true,
  "sortOrder": 20,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-tshirt-5kg",
  "slug": "pakety-mayka-sanpack-5kg",
  "sku": "SP-MS-5KG-100",
  "status": "published",
  "categoryId": "cat-tshirt-bags",
  "categorySlug": "pakety-mayka",
  "titleRu": "Пакеты «Майка» SANPACK ULTRA 5 кг (29 × 47 см, 100 шт)",
  "titleUz": "SANPACK ULTRA «Mayka» paketlari 5 kg (29 × 47 sm, 100 dona)",
  "shortDescriptionRu": "Ходовой размер пакета маечного типа под нагрузку до 5 кг.",
  "shortDescriptionUz": "5 kg gacha yuklama uchun ommabop mayka paketi.",
  "descriptionRu": "Универсальные пакеты «Майка» 5 кг SANPACK ULTRA для розничной торговли и фасовки.",
  "descriptionUz": "Chakana savdo va qadoqlash uchun universal 5 kg li mayka paketlar.",
  "images": [
    "/catalog/commercial_packaging_3.webp"
  ],
  "mainImage": "/catalog/commercial_packaging_3.webp",
  "attributes": {
      "material": "ПНД",
      "thickness": "12 мкм",
      "horeca_category": "Пакеты Майка"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 50,
  "salesUnit": "упаковка",
  "featured": true,
  "newProduct": false,
  "ownProduction": true,
  "sortOrder": 21,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-tshirt-10kg",
  "slug": "pakety-mayka-sanpack-10kg",
  "sku": "SP-MS-10KG-100",
  "status": "published",
  "categoryId": "cat-tshirt-bags",
  "categorySlug": "pakety-mayka",
  "titleRu": "Пакеты «Майка» SANPACK ULTRA 10 кг (33 × 57 см, 100 шт)",
  "titleUz": "SANPACK ULTRA «Mayka» paketlari 10 kg (33 × 57 sm, 100 dona)",
  "shortDescriptionRu": "Большие прочные пакеты до 10 кг для габаритных товаров.",
  "shortDescriptionUz": "Katta tovarlar uchun 10 kg gacha mustahkam paketlar.",
  "descriptionRu": "Вместительные пакеты маечного типа SANPACK ULTRA на 10 кг для магазинов одежды, продуктов и рынков.",
  "descriptionUz": "Kiyim va oziq-ovqat do'konlari uchun 10 kg li keng mayka paketlar.",
  "images": [
    "/catalog/commercial_packaging_4.webp"
  ],
  "mainImage": "/catalog/commercial_packaging_4.webp",
  "attributes": {
      "material": "ПНД",
      "thickness": "15 мкм",
      "horeca_category": "Пакеты Майка"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 30,
  "salesUnit": "упаковка",
  "featured": true,
  "newProduct": false,
  "ownProduction": true,
  "sortOrder": 22,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-tshirt-25kg",
  "slug": "pakety-mayka-sanpack-25kg",
  "sku": "SP-MS-25KG-25",
  "status": "published",
  "categoryId": "cat-tshirt-bags",
  "categorySlug": "pakety-mayka",
  "titleRu": "Пакеты «Майка» SANPACK ULTRA 25 кг (46 × 70 см, 25 шт)",
  "titleUz": "SANPACK ULTRA «Mayka» paketlari 25 kg (46 × 70 sm, 25 dona)",
  "shortDescriptionRu": "Усиленные грузовая пакеты майка повышенной толщины до 25 кг.",
  "shortDescriptionUz": "25 kg gacha mo'ljallangan o'ta qalin yuk paketlari.",
  "descriptionRu": "Грузовые суперпрочные пакеты SANPACK ULTRA 25 кг для тяжелых коробок, бакалеи и строительных материалов.",
  "descriptionUz": "Og'ir qutilar va baqolchilik uchun SANPACK ULTRA 25 kg li yuk paketlari.",
  "images": [
    "/catalog/commercial_packaging_5.webp"
  ],
  "mainImage": "/catalog/commercial_packaging_5.webp",
  "attributes": {
      "material": "ПНД",
      "thickness": "20 мкм",
      "horeca_category": "Пакеты Майка"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 20,
  "salesUnit": "упаковка",
  "featured": false,
  "newProduct": false,
  "ownProduction": true,
  "sortOrder": 23,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-tshirt-50kg",
  "slug": "pakety-mayka-sanpack-50kg",
  "sku": "SP-MS-50KG-25",
  "status": "published",
  "categoryId": "cat-tshirt-bags",
  "categorySlug": "pakety-mayka",
  "titleRu": "Пакеты «Майка» SANPACK ULTRA 50 кг (52 × 100 см, 25 шт)",
  "titleUz": "SANPACK ULTRA «Mayka» paketlari 50 kg (52 × 100 sm, 25 dona)",
  "shortDescriptionRu": "Максимальный размер грузового пакета майка до 50 кг.",
  "shortDescriptionUz": "50 kg gacha maksimal o'lchamdagi yuk paketi.",
  "descriptionRu": "Огромные суперпрочные пакеты майка SANPACK ULTRA 50 кг для оптовых рынков и оптовых складов.",
  "descriptionUz": "Ulgurji bozorlar va omborlar uchun 50 kg li ulkan mustahkam paketlar.",
  "images": [
    "/catalog/commercial_packaging_6.webp"
  ],
  "mainImage": "/catalog/commercial_packaging_6.webp",
  "attributes": {
      "material": "ПНД",
      "thickness": "12 мкм",
      "horeca_category": "Пакеты Майка"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 20,
  "salesUnit": "упаковка",
  "featured": false,
  "newProduct": false,
  "ownProduction": true,
  "sortOrder": 24,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-roll-1927",
  "slug": "rulonnye-pakety-sanpack-19x27",
  "sku": "SP-RB-1927-222",
  "status": "published",
  "categoryId": "cat-tshirt-bags",
  "categorySlug": "pakety-mayka",
  "titleRu": "Рулонные фасовочные пакеты SANPACK 19 × 27 см (222 шт)",
  "titleUz": "SANPACK rulonli qadoqlash paketlari 19 × 27 sm (222 dona)",
  "shortDescriptionRu": "Прозрачные фасовочные пакеты в рулоне для овощей, фруктов и весовой продукции.",
  "shortDescriptionUz": "Sabzavot va mevalar uchun rulondagi shaffof paketlar.",
  "descriptionRu": "Фасовочные полиэтиленовые пакеты в рулоне SANPACK (222 штуки). Легкий отрыв по перфорации.",
  "descriptionUz": "SANPACK rulonli polietilen qadoq paketlari (222 dona). Teshik bo'ylab oson uzish.",
  "images": [
    "/catalog/commercial_packaging_8.webp"
  ],
  "mainImage": "/catalog/commercial_packaging_8.webp",
  "attributes": {
      "material": "ПНД",
      "thickness": "8 мкм",
      "packaging_type": "Рулон",
      "horeca_category": "Пакеты Майка"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 20,
  "salesUnit": "рулон",
  "featured": false,
  "newProduct": false,
  "ownProduction": true,
  "sortOrder": 25,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-roll-2838",
  "slug": "rulonnye-pakety-sanpack-28x38",
  "sku": "SP-RB-2838-303",
  "status": "published",
  "categoryId": "cat-tshirt-bags",
  "categorySlug": "pakety-mayka",
  "titleRu": "Рулонные фасовочные пакеты SANPACK ULTRA 28 × 38 см (303 шт)",
  "titleUz": "SANPACK ULTRA rulonli qadoqlash paketlari 28 × 38 sm (303 dona)",
  "shortDescriptionRu": "Большой экономичный рулон фасовочных пакетов 303 штуки.",
  "shortDescriptionUz": "303 donalik qadoq paketlarining katta tejamkor ruloni.",
  "descriptionRu": "Прозрачные пищевые пакеты в рулоне 303 штуки SANPACK ULTRA для супермаркетов и пекарен.",
  "descriptionUz": "Supermarketlar va novvoyxonalar uchun SANPACK ULTRA 303 donalik rulonli paketlar.",
  "images": [
    "/catalog/commercial_packaging_9.webp"
  ],
  "mainImage": "/catalog/commercial_packaging_9.webp",
  "attributes": {
      "material": "ПНД",
      "thickness": "8 мкм",
      "packaging_type": "Рулон",
      "horeca_category": "Пакеты Майка"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 20,
  "salesUnit": "рулон",
  "featured": true,
  "newProduct": false,
  "ownProduction": true,
  "sortOrder": 26,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-pizza-bags",
  "slug": "pakety-dlya-pitssy-sanpack",
  "sku": "SP-PZ-BAG",
  "status": "published",
  "categoryId": "cat-tshirt-bags",
  "categorySlug": "pakety-mayka",
  "titleRu": "Пакеты с широким дном для пиццы и контейнеров SANPACK",
  "titleUz": "Pitsa va konteynerlar uchun keng tubli SANPACK paketlari",
  "shortDescriptionRu": "Специальные пакеты с широкой донной складкой под коробки с пиццей.",
  "shortDescriptionUz": "Pitsa qutilari uchun keng tubli maxsus paketlar.",
  "descriptionRu": "Удобные пакеты для курьеров доставки пиццы и пирогов. Коробки лежат ровно горизонтально без переворачивания.",
  "descriptionUz": "Pitsa va piroglarni yetkazib beruvchi kuryerlar uchun qulay paketlar.",
  "images": [
    "/catalog/extracted_p6_img18.jpeg"
  ],
  "mainImage": "/catalog/extracted_p6_img18.jpeg",
  "attributes": {
      "material": "ПНД",
      "thickness": "20 мкм",
      "packaging_type": "Пачка",
      "horeca_category": "Пакеты Майка"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 50,
  "salesUnit": "упаковка",
  "featured": true,
  "newProduct": true,
  "ownProduction": true,
  "sortOrder": 27,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-rice-lazer",
  "slug": "ris-lazer-otbornyy",
  "sku": "SP-RICE-LAZER",
  "status": "published",
  "categoryId": "cat-groceries",
  "categorySlug": "bakaleya",
  "titleRu": "Рис «Лазер» отборный для плова",
  "titleUz": "Palov uchun «Lazer» saralangan guruchi",
  "shortDescriptionRu": "Элитный национальный сорт длиннозерного риса «Лазер».",
  "shortDescriptionUz": "«Lazer» uzun donli elita guruch navi.",
  "descriptionRu": "Отборный рис «Лазер» высшей очистки. Идеален для традиционного узбекского праздничного плова в ресторанах и чайханах.",
  "descriptionUz": "Oliy tozalangan saralangan «Lazer» guruchi. An'anaviy o'zbek palovi uchun ideal.",
  "images": [
    "/catalog/extracted_p7_img1.jpeg"
  ],
  "mainImage": "/catalog/extracted_p7_img1.jpeg",
  "attributes": {
      "horeca_category": "Бакалея и Мука",
      "weight": "1 кг",
      "packaging_type": "Пачка"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 2,
  "salesUnit": "мешок",
  "featured": true,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 30,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-rice-alanga",
  "slug": "ris-alanga-otbornyy",
  "sku": "SP-RICE-ALANGA",
  "status": "published",
  "categoryId": "cat-groceries",
  "categorySlug": "bakaleya",
  "titleRu": "Рис «Аланга» отборный",
  "titleUz": "«Alanga» saralangan guruchi",
  "shortDescriptionRu": "Популярный сорт риса «Аланга» для ежедневного меню HoReCa.",
  "shortDescriptionUz": "HoReCa kunlik menyusi uchun mashhur «Alanga» guruchi.",
  "descriptionRu": "Рис «Аланга» отличающийся прекрасным впитыванием масла и ароматов при приготовлении плова и гарниров.",
  "descriptionUz": "Palov va garnirlar tayyorlashda yog' va iforni ajoyib shimuvchi «Alanga» guruchi.",
  "images": [
    "/catalog/extracted_p7_img2.jpeg"
  ],
  "mainImage": "/catalog/extracted_p7_img2.jpeg",
  "attributes": {
      "horeca_category": "Бакалея и Мука",
      "weight": "1 кг",
      "packaging_type": "Пачка"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 2,
  "salesUnit": "мешок",
  "featured": true,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 31,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-grechka",
  "slug": "grechka-otbornaya",
  "sku": "SP-GRECHKA",
  "status": "published",
  "categoryId": "cat-groceries",
  "categorySlug": "bakaleya",
  "titleRu": "Гречка ядрица отборная",
  "titleUz": "Saralangan grechka yadritsa",
  "shortDescriptionRu": "Чистая пропаренная гречневая крупа высшего сорта.",
  "shortDescriptionUz": "Oliy navli toza bug'langan grechka yarmasi.",
  "descriptionRu": "Отборная гречневая крупа без мусора и примесей для столовых, отелей и ресторанов.",
  "descriptionUz": "Oshxonalar va restoranlar uchun aralashmalarsiz saralangan grechka yarmasi.",
  "images": [
    "/catalog/extracted_p7_img3.jpeg"
  ],
  "mainImage": "/catalog/extracted_p7_img3.jpeg",
  "attributes": {
      "horeca_category": "Бакалея и Мука",
      "weight": "1 кг",
      "packaging_type": "Пачка"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 5,
  "salesUnit": "мешок",
  "featured": false,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 32,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-flour-dani-nan",
  "slug": "muka-dani-nan-vysshiy-sort",
  "sku": "SP-FLOUR-DANI",
  "status": "published",
  "categoryId": "cat-groceries",
  "categorySlug": "bakaleya",
  "titleRu": "Мука пшеничная «ДАНИ НАН» (Высший / 1-сорт)",
  "titleUz": "«DANI NAN» bug‘doy uni (Oliy / 1-nav)",
  "shortDescriptionRu": "Казахстанская пшеничная мука высокого качества для лепёшек, самсы и выпечки.",
  "shortDescriptionUz": "Lepyoshka, somsa va pishiriqlar uchun Qozog'iston bug'doy uni.",
  "descriptionRu": "Мука «ДАНИ НАН» (ТОО «Дани-Нан» Казахстан) обладает отличными хлебопекарными свойствами и высокой клейковиной.",
  "descriptionUz": "«DANI NAN» uni yuqori kleykovinaga ega ajoyib non pishirish xususiyatlariga ega.",
  "images": [
    "/catalog/extracted_p7_img9.jpeg"
  ],
  "mainImage": "/catalog/extracted_p7_img9.jpeg",
  "attributes": {
      "horeca_category": "Бакалея и Мука",
      "weight": "5 кг",
      "packaging_type": "Пачка"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 2,
  "salesUnit": "мешок",
  "featured": true,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 33,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-flour-motabar",
  "slug": "muka-motabar-vysshiy-sort",
  "sku": "SP-FLOUR-MOTABAR",
  "status": "published",
  "categoryId": "cat-groceries",
  "categorySlug": "bakaleya",
  "titleRu": "Мука пшеничная MO’TABAR (50 кг)",
  "titleUz": "MO’TABAR bug‘doy uni (50 kg)",
  "shortDescriptionRu": "Отборная мука высшего и 1 сорта MO’TABAR для профессиональных пекарен.",
  "shortDescriptionUz": "Professional novvoyxonalar uchun MO’TABAR oliy va 1-navli uni.",
  "descriptionRu": "Мука MO’TABAR идеальна для замеса пышного теста, пиццы, пасты и национальной выпечки.",
  "descriptionUz": "MO’TABAR uni yumshoq xamir, pitsa va milliy pishiriqlar uchun ideal.",
  "images": [
    "/catalog/extracted_p7_img8.jpeg"
  ],
  "mainImage": "/catalog/extracted_p7_img8.jpeg",
  "attributes": {
      "horeca_category": "Бакалея и Мука",
      "weight": "50 кг",
      "packaging_type": "Мешок 50 кг"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 2,
  "salesUnit": "мешок",
  "featured": false,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 34,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-flour-altyn-dan",
  "slug": "muka-altyn-dan-vysshiy-sort",
  "sku": "SP-FLOUR-ALTYN",
  "status": "published",
  "categoryId": "cat-groceries",
  "categorySlug": "bakaleya",
  "titleRu": "Мука пшеничная «АЛТЫН ДАН» (50 кг)",
  "titleUz": "«ALTYN DAN» bug‘doy uni (50 kg)",
  "shortDescriptionRu": "Известный бренд Казахстанской пшеничной муки высшего сорта.",
  "shortDescriptionUz": "Qozog'iston oliy navli bug'doy unining mashhur brendi.",
  "descriptionRu": "Мука «АЛТЫН ДАН» гарантирует стабильное качество хлебобулочных изделий.",
  "descriptionUz": "«ALTYN DAN» uni non-bulochka mahsulotlarining barqaror sifatini kafolatlaydi.",
  "images": [
    "/catalog/extracted_p7_img10.jpeg"
  ],
  "mainImage": "/catalog/extracted_p7_img10.jpeg",
  "attributes": {
      "horeca_category": "Бакалея и Мука",
      "weight": "50 кг",
      "packaging_type": "Мешок 50 кг"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 2,
  "salesUnit": "мешок",
  "featured": false,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 35,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-oleyna-oil",
  "slug": "maslo-podsolnechnoe-oleyna",
  "sku": "SP-OIL-OLEYNA",
  "status": "published",
  "categoryId": "cat-groceries",
  "categorySlug": "bakaleya",
  "titleRu": "Подсолнечное масло «ОЛЕЙНА»",
  "titleUz": "«OLEYNA» kungaboqar yog‘i",
  "shortDescriptionRu": "Рафинированное дезодорированное подсолнечное масло без запаха.",
  "shortDescriptionUz": "Hidsiz rafinatsiyalangan kungaboqar yog'i.",
  "descriptionRu": "Подсолнечное масло «ОЛЕЙНА» идеально для жарки во фритюре, пассеровки и заправки салатов.",
  "descriptionUz": "«OLEYNA» kungaboqar yog'i qovurish va salatlar uchun ideal.",
  "images": [
    "/catalog/extracted_p8_img2.jpeg"
  ],
  "mainImage": "/catalog/extracted_p8_img2.jpeg",
  "attributes": {
      "horeca_category": "Бакалея и Мука",
      "weight": "1 кг",
      "packaging_type": "Бутылка 1 л"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 1,
  "salesUnit": "коробка",
  "featured": true,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 36,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-cheese-svalia",
  "slug": "syr-svalya-polutverdyy-3kg",
  "sku": "SP-CHS-SVALIA",
  "status": "published",
  "categoryId": "cat-cheeses",
  "categorySlug": "syry-i-maslo",
  "titleRu": "Сыр «СВАЛЯ» полутвердый 45% (брус 3 кг)",
  "titleUz": "«SVALYA» yarim qattiq pishlog‘i 45% (3 kg)",
  "shortDescriptionRu": "Классический европейский полутвердый сыр для нарезки и пиццы.",
  "shortDescriptionUz": "Pitsa va kesish uchun klassik yevropa pishlog'i.",
  "descriptionRu": "Сыр СВАЛЯ с нежным сливочным вкусом и равномерным ажурным рисунком. Отлично плавится.",
  "descriptionUz": "Yumshoq qaymoqli ta'mga ega SVALYA pishlog'i. Ajoyib eriydi.",
  "images": [
    "/catalog/extracted_p9_img1.jpeg"
  ],
  "mainImage": "/catalog/extracted_p9_img1.jpeg",
  "attributes": {
      "horeca_category": "Сыры и Масло",
      "weight": "3 кг",
      "packaging_type": "Брус"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 1,
  "salesUnit": "брус",
  "featured": true,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 40,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-cheese-viola",
  "slug": "syr-viola-plavlenyy-400g",
  "sku": "SP-CHS-VIOLA",
  "status": "published",
  "categoryId": "cat-cheeses",
  "categorySlug": "syry-i-maslo",
  "titleRu": "Сыр плавленный VIOLA Creamy 400 гр (60%)",
  "titleUz": "VIOLA eritilgan pishlog‘i Creamy 400 gr (60%)",
  "shortDescriptionRu": "Легендарный сливочный плавленный сыр VIOLA в ванночке.",
  "shortDescriptionUz": "Vannochkadagi afsonaviy qaymoqli VIOLA pishlog'i.",
  "descriptionRu": "Плавленый сыр VIOLA с насыщенным сливочным вкусом для бутербродов, супов-пюре и соусов.",
  "descriptionUz": "Buterbrodlar, sho'rvalar va souslar uchun boy qaymoqli VIOLA pishlog'i.",
  "images": [
    "/catalog/extracted_p9_img5.jpeg"
  ],
  "mainImage": "/catalog/extracted_p9_img5.jpeg",
  "attributes": {
      "horeca_category": "Сыры и Масло",
      "weight": "400 гр",
      "packaging_type": "Контейнер / Лоток"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 6,
  "salesUnit": "штука",
  "featured": true,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 41,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-cheese-valio-burger",
  "slug": "syr-valio-cheese-burger-150g",
  "sku": "SP-CHS-VAL-BRG",
  "status": "published",
  "categoryId": "cat-cheeses",
  "categorySlug": "syry-i-maslo",
  "titleRu": "Сыр VALIO Cheese Burger ломтиками 150 гр",
  "titleUz": "VALIO Cheese Burger pishloq bo‘laklari 150 gr",
  "shortDescriptionRu": "Порционные ломтики сыра для бургеров и сэндвичей.",
  "shortDescriptionUz": "Burger va sendvichlar uchun pishloq bo'laklari.",
  "descriptionRu": "Сырные ломтики VALIO Cheese Burger мгновенно плавятся на горячей котлете, придавая бургеру аппетитный вид.",
  "descriptionUz": "VALIO Cheese Burger pishloq bo'laklari issiq kotletda darhol eriydi.",
  "images": [
    "/catalog/extracted_p9_img6.jpeg"
  ],
  "mainImage": "/catalog/extracted_p9_img6.jpeg",
  "attributes": {
      "horeca_category": "Сыры и Масло",
      "weight": "150 гр",
      "packaging_type": "Пачка"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 10,
  "salesUnit": "упаковка",
  "featured": true,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 42,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-cheese-fitaki",
  "slug": "syr-fitaki-original-500g",
  "sku": "SP-CHS-FITAKI",
  "status": "published",
  "categoryId": "cat-cheeses",
  "categorySlug": "syry-i-maslo",
  "titleRu": "Сыр FITAKI Original мягкий рассольный 500 гр",
  "titleUz": "FITAKI Original yumshoq pishlog‘i 500 gr",
  "shortDescriptionRu": "Мягкий сыр для греческого салата и закусок mediterrane.",
  "shortDescriptionUz": "Yunan salati va zakuskalar uchun yumshoq pishloq.",
  "descriptionRu": "Нежный сыр FITAKI с приятной солоноватой ноткой и кремовой текстурой для салатов.",
  "descriptionUz": "Salatlar uchun yoqimli sho'rtang va kremli teksturaga ega FITAKI pishlog'i.",
  "images": [
    "/catalog/extracted_p9_img3.jpeg"
  ],
  "mainImage": "/catalog/extracted_p9_img3.jpeg",
  "attributes": {
      "horeca_category": "Сыры и Масло",
      "weight": "500 гр",
      "packaging_type": "Контейнер / Лоток"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 6,
  "salesUnit": "упаковка",
  "featured": false,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 43,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-cheese-dorblu",
  "slug": "syr-dorblu-classic-2-5kg",
  "sku": "SP-CHS-DORBLU",
  "status": "published",
  "categoryId": "cat-cheeses",
  "categorySlug": "syry-i-maslo",
  "titleRu": "Сыр DORBLU Classic полутвердый с голубой плесенью 2.5 кг",
  "titleUz": "DORBLU Classic ko‘k mog‘orli pishloq 2.5 kg",
  "shortDescriptionRu": "Знаменитый немецкий сыр с благородной голубой плесенью.",
  "shortDescriptionUz": "Olijanob ko'k mog'orli mashhur olmon pishlog'i.",
  "descriptionRu": "Сыр DORBLU с пикантным пряным вкусом для сырных тарелок, соусов к пасте и стекам.",
  "descriptionUz": "Pishloq tarelkasi va souslar uchun o'tkir ta'mga ega DORBLU pishlog'i.",
  "images": [
    "/catalog/extracted_p9_img9.jpeg"
  ],
  "mainImage": "/catalog/extracted_p9_img9.jpeg",
  "attributes": {
      "horeca_category": "Сыры и Масло",
      "weight": "2.5 кг",
      "packaging_type": "Брус"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 1,
  "salesUnit": "головка",
  "featured": true,
  "newProduct": true,
  "ownProduction": false,
  "sortOrder": 44,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-butter-valio-500g",
  "slug": "maslo-slivochnoe-valio-500g",
  "sku": "SP-BTR-VAL-500",
  "status": "published",
  "categoryId": "cat-cheeses",
  "categorySlug": "syry-i-maslo",
  "titleRu": "Масло сливочное VALIO 82% (500 гр)",
  "titleUz": "VALIO sariyog‘i 82% (500 gr)",
  "shortDescriptionRu": "Премиальное сладко-сливочное несоленое масло VALIO 82%.",
  "shortDescriptionUz": "VALIO 82% oliy navli sariyog'.",
  "descriptionRu": "Натуральное сливочное масло VALIO из чистых сливок для кремов, выпечки и соусов.",
  "descriptionUz": "Kremlar, pishiriqlar va souslar uchun toza qaymoqdan tayyorlangan tabiiy VALIO sariyog'i.",
  "images": [
    "/catalog/extracted_p10_img4.jpeg"
  ],
  "mainImage": "/catalog/extracted_p10_img4.jpeg",
  "attributes": {
      "horeca_category": "Сыры и Масло",
      "weight": "500 гр",
      "packaging_type": "Пачка"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 5,
  "salesUnit": "пачка",
  "featured": true,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 45,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-green-rukola",
  "slug": "rukola-svezhaya-novagreen",
  "sku": "SP-GRN-RUKOLA",
  "status": "published",
  "categoryId": "cat-greens",
  "categorySlug": "svezhaya-zelen",
  "titleRu": "Рукола свежая Novagreen (250/500 гр)",
  "titleUz": "Novagreen yangi rukola (250/500 gr)",
  "shortDescriptionRu": "Пряная свежая рукола с ореховым оттенком прямо из теплиц.",
  "shortDescriptionUz": "Issiqxonalardan yong'oq ta'mli yangi rukola.",
  "descriptionRu": "Свежая охлажденная рукола Novagreen для пиццы, салатов и украшения ресторанных блюд.",
  "descriptionUz": "Pitsa va salatlar uchun Novagreen yangi sovutilgan rukolasi.",
  "images": [
    "/catalog/extracted_p11_img1.jpeg"
  ],
  "mainImage": "/catalog/extracted_p11_img1.jpeg",
  "attributes": {
      "horeca_category": "Свежая зелень Novagreen",
      "weight": "250 гр",
      "packaging_type": "Контейнер / Лоток"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 2,
  "salesUnit": "упаковка",
  "featured": true,
  "newProduct": true,
  "ownProduction": false,
  "sortOrder": 50,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-green-iceberg",
  "slug": "salat-aysberg-novagreen",
  "sku": "SP-GRN-ICEBERG",
  "status": "published",
  "categoryId": "cat-greens",
  "categorySlug": "svezhaya-zelen",
  "titleRu": "Салат «Айсберг» Novagreen (500 гр)",
  "titleUz": "«Aysberg» salati Novagreen (500 gr)",
  "shortDescriptionRu": "Хрустящие сочные кочаны салата Айсберг для цезаря и бургеров.",
  "shortDescriptionUz": "Sezar va burgerlar uchun qarsillama sersuv Aysberg salati.",
  "descriptionRu": "Отборный салат Айсберг Novagreen в индивидуальной защитной упаковке.",
  "descriptionUz": "Himoya qadoqidagi Novagreen saralangan Aysberg salati.",
  "images": [
    "/catalog/extracted_p11_img2.jpeg"
  ],
  "mainImage": "/catalog/extracted_p11_img2.jpeg",
  "attributes": {
      "horeca_category": "Свежая зелень Novagreen",
      "weight": "500 гр",
      "packaging_type": "Контейнер / Лоток"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 2,
  "salesUnit": "упаковка",
  "featured": true,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 51,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-green-mint",
  "slug": "myata-svezhaya-novagreen",
  "sku": "SP-GRN-MINT",
  "status": "published",
  "categoryId": "cat-greens",
  "categorySlug": "svezhaya-zelen",
  "titleRu": "Мята свежая ароматная Novagreen (пучок 60/500 гр)",
  "titleUz": "Novagreen yangi xushbo‘y yalpiz (60/500 gr)",
  "shortDescriptionRu": "Ароматная мятная зелень для коктейлей, лимонадов и десертов.",
  "shortDescriptionUz": "Kokteyllar va desertlar uchun xushbo'y yalpiz.",
  "descriptionRu": "Свежесрезанная мята Novagreen высокой ароматичности для барной карты и кондитерских.",
  "descriptionUz": "Bar va konditerlar uchun Novagreen yangi uzilgan xushbo'y yalpizi.",
  "images": [
    "/catalog/extracted_p12_img1.jpeg"
  ],
  "mainImage": "/catalog/extracted_p12_img1.jpeg",
  "attributes": {
      "horeca_category": "Свежая зелень Novagreen",
      "weight": "60 гр",
      "packaging_type": "Контейнер / Лоток"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 5,
  "salesUnit": "пучок",
  "featured": false,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 52,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-green-rosemary",
  "slug": "rozmarin-svezhiy-novagreen",
  "sku": "SP-GRN-ROSEMARY",
  "status": "published",
  "categoryId": "cat-greens",
  "categorySlug": "svezhaya-zelen",
  "titleRu": "Розмарин свежий Novagreen (20/250/500 гр)",
  "titleUz": "Novagreen yangi rozmarin (20/250/500 gr)",
  "shortDescriptionRu": "Свежие веточки розмарина для запекания мяса, стейков и соусов.",
  "shortDescriptionUz": "Go'sht va steyklar uchun yangi rozmarin shoxchalari.",
  "descriptionRu": "Пряный розмарин Novagreen подчеркнет вкус мясных и рыбных блюд на гриле.",
  "descriptionUz": "Novagreen rozmarini grildagi go'sht va baliq taomlari ta'mini oshiradi.",
  "images": [
    "/catalog/extracted_p12_img3.jpeg"
  ],
  "mainImage": "/catalog/extracted_p12_img3.jpeg",
  "attributes": {
      "horeca_category": "Свежая зелень Novagreen",
      "weight": "20 гр",
      "packaging_type": "Контейнер / Лоток"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 2,
  "salesUnit": "упаковка",
  "featured": false,
  "newProduct": false,
  "ownProduction": false,
  "sortOrder": 53,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-microgreen-micro",
  "slug": "mikrozelen-amarant-gorokh-brokkoli",
  "sku": "SP-GRN-MICRO",
  "status": "published",
  "categoryId": "cat-greens",
  "categorySlug": "svezhaya-zelen",
  "titleRu": "Микрозелень Novagreen (Амарант, Горох, Брокколи, Кресс-салат)",
  "titleUz": "Novagreen mikroko‘katlari (Amarant, No‘xat, Brokkoli)",
  "shortDescriptionRu": "Живая микрозелень в контейнерах для высокой кухни и украшения блюд.",
  "shortDescriptionUz": "Taomlarni bezash uchun konteynerdagi tirik mikroko'katlar.",
  "descriptionRu": "Микрозелень Novagreen богата витаминами и придает эффектный визуал подаче ресторанных блюд.",
  "descriptionUz": "Novagreen mikroko'katlari vitaminlarga boy va taom ko'rinishini bezaydi.",
  "images": [
    "/catalog/extracted_p12_img7.jpeg"
  ],
  "mainImage": "/catalog/extracted_p12_img7.jpeg",
  "attributes": {
      "horeca_category": "Свежая зелень Novagreen",
      "weight": "60 гр",
      "packaging_type": "Контейнер / Лоток"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 5,
  "salesUnit": "лоток",
  "featured": true,
  "newProduct": true,
  "ownProduction": false,
  "sortOrder": 54,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
  {
  "id": "prod-branding-nova-print",
  "slug": "poligrafiya-upakovka-i-brendirovanie-nova-print",
  "sku": "SP-NOVA-PRINT",
  "status": "published",
  "categoryId": "cat-branding",
  "categorySlug": "branding-polygraphy",
  "titleRu": "Комплексные услуги полиграфии и брендирования Nova Print",
  "titleUz": "Nova Print polagrafiya va brendlash kompleks xizmatlari",
  "shortDescriptionRu": "Печать пакетов, меню, этикеток, формы, брендирование авто и фасадов.",
  "shortDescriptionUz": "Paketlar, menyu, etiketkalar bosish va avto brendlash.",
  "descriptionRu": "Sanpack совместно с партнером Nova Print предлагает разработку дизайна и набором полиграфических услуг под ключ: брендированные пакеты, крафт-упаковка, стаканчики, стикеры, меню, корпоративная одежда и оформление вывесок.",
  "descriptionUz": "Sanpack va Nova Print hamkorligida brendlangan paketlar, menyu, stikerlar va kiyimlar tayyorlash.",
  "images": [
    "/catalog/extracted_p14_img1.jpeg"
  ],
  "mainImage": "/catalog/extracted_p14_img1.jpeg",
  "attributes": {
      "horeca_category": "Брендирование Nova Print"
    },
  "variants": [],
  "currency": "сум",
  "showPrice": false,
  "stockStatus": "in_stock",
  "minimumOrder": 1,
  "salesUnit": "услуга",
  "featured": true,
  "newProduct": true,
  "ownProduction": true,
  "sortOrder": 60,
  "createdAt": new Date().toISOString(),
  "updatedAt": new Date().toISOString()
},
];
